/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.safemoney.gui;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import static com.safemoney.gui.IniciarSesion.user;

/**
 *
 * @author JOHANNA
 */

public class frmAhorrosFijos extends javax.swing.JFrame {


    //Capturamos la ruta donde se encuentra la imagen que queremos colocar como icono del JFrame.
    public final String ruta = "/com/safemoney/imagenes/logo.png";
    /**
     * Creates new form frmAhorrosFijos
     */
    public frmAhorrosFijos() {
        
        this.setLocationRelativeTo(null);
        
        initComponents();
        lblDineroAhorrosFijos.setText(String.valueOf(user.ahorroFijo.getCantidad()));
        txtDescripcionAF.setText(user.ahorroFijo.getDescripcion());
        
        //Capturar imagen con ayuda de un toolkit que recupera una imagen 
        Image icono = Toolkit.getDefaultToolkit().getImage(getClass().getResource(ruta));
        //Mostrar imagen en el icono del JFrame
        setIconImage(icono);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblRetirarAF = new javax.swing.JLabel();
        bntRetirar = new javax.swing.JButton();
        btnRetirarSuma = new javax.swing.JButton();
        btnRetirarResta = new javax.swing.JButton();
        lblAgregarAF = new javax.swing.JLabel();
        btnAgregarSuma = new javax.swing.JButton();
        btnAgregarResta = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        iconLogo = new javax.swing.JLabel();
        lblDineroAhorrosFijos = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDescripcionAF = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pnlAtras = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 0, 204));
        setLocation(new java.awt.Point(0, 0));
        setSize(new java.awt.Dimension(1536, 864));

        jPanel1.setBackground(new java.awt.Color(102, 0, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRetirarAF.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        lblRetirarAF.setForeground(new java.awt.Color(255, 255, 255));
        lblRetirarAF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRetirarAF.setText("0");
        jPanel1.add(lblRetirarAF, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 520, 330, 50));

        bntRetirar.setFont(new java.awt.Font("Chewy", 0, 36)); // NOI18N
        bntRetirar.setText("Retirar");
        bntRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRetirarActionPerformed(evt);
            }
        });
        jPanel1.add(bntRetirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 600, 170, 50));

        btnRetirarSuma.setFont(new java.awt.Font("Chewy", 0, 24)); // NOI18N
        btnRetirarSuma.setText("+");
        btnRetirarSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarSumaActionPerformed(evt);
            }
        });
        jPanel1.add(btnRetirarSuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 520, 70, 50));

        btnRetirarResta.setFont(new java.awt.Font("Chewy", 0, 24)); // NOI18N
        btnRetirarResta.setText("-");
        btnRetirarResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarRestaActionPerformed(evt);
            }
        });
        jPanel1.add(btnRetirarResta, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 520, 70, 50));

        lblAgregarAF.setFont(new java.awt.Font("Open Sans", 0, 48)); // NOI18N
        lblAgregarAF.setForeground(new java.awt.Color(255, 255, 255));
        lblAgregarAF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAgregarAF.setText("0");
        jPanel1.add(lblAgregarAF, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 310, 330, 50));

        btnAgregarSuma.setFont(new java.awt.Font("Chewy", 0, 24)); // NOI18N
        btnAgregarSuma.setText("+");
        btnAgregarSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarSumaActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarSuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 310, 70, 50));

        btnAgregarResta.setFont(new java.awt.Font("Chewy", 0, 24)); // NOI18N
        btnAgregarResta.setText("-");
        btnAgregarResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarRestaActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarResta, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 310, 70, 50));

        btnAgregar.setFont(new java.awt.Font("Chewy", 0, 36)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 390, 170, 50));

        iconLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/safemoney/imagenes/alcanciaCerditoPrincipal.png"))); // NOI18N
        jPanel1.add(iconLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, 420, 390));

        lblDineroAhorrosFijos.setFont(new java.awt.Font("Chewy", 0, 48)); // NOI18N
        lblDineroAhorrosFijos.setForeground(new java.awt.Color(255, 255, 255));
        lblDineroAhorrosFijos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDineroAhorrosFijos.setText("0");
        jPanel1.add(lblDineroAhorrosFijos, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 160, 440, 40));

        txtDescripcionAF.setFont(new java.awt.Font("Open Sans", 0, 24)); // NOI18N
        jScrollPane3.setViewportView(txtDescripcionAF);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 390, 370));

        jLabel2.setBackground(new java.awt.Color(0, 204, 255));
        jLabel2.setFont(new java.awt.Font("Chewy", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Descripción");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 180, 50));

        jLabel3.setBackground(new java.awt.Color(0, 204, 255));
        jLabel3.setFont(new java.awt.Font("Chewy", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cantidad");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 110, 150, 30));

        jLabel5.setBackground(new java.awt.Color(0, 204, 255));
        jLabel5.setFont(new java.awt.Font("Chewy", 0, 50)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/safemoney/imagenes/ImagenAhorrosFijos.png"))); // NOI18N
        jLabel5.setText("AHORROS FIJOS");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 450, 140));

        pnlAtras.setBackground(new java.awt.Color(255, 58, 58));
        pnlAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlAtrasMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Chewy", 0, 80)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("<-");

        javax.swing.GroupLayout pnlAtrasLayout = new javax.swing.GroupLayout(pnlAtras);
        pnlAtras.setLayout(pnlAtrasLayout);
        pnlAtrasLayout.setHorizontalGroup(
            pnlAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAtrasLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        pnlAtrasLayout.setVerticalGroup(
            pnlAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAtrasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel1.add(pnlAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1529, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 864, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    
    private void btnAgregarSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarSumaActionPerformed
        int cantActual = Integer.parseInt(lblAgregarAF.getText());
        lblAgregarAF.setText(String.valueOf(cantActual + 1000));


    }//GEN-LAST:event_btnAgregarSumaActionPerformed

    private void btnAgregarRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarRestaActionPerformed
        int cantActual = Integer.parseInt(lblAgregarAF.getText());
        
        if ( cantActual > 0) {
            lblAgregarAF.setText(String.valueOf(cantActual - 1000));      
        } else {
            JOptionPane.showMessageDialog(this, "No se puede disminuir la cantidad a numeros negativos, recuerda que para agregar dinero debe ser positivo.", "NO SE ACEPTA CANTIDADES NEGATIVAS", HEIGHT);
        }

    }//GEN-LAST:event_btnAgregarRestaActionPerformed

    private void btnRetirarRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarRestaActionPerformed
        int cantActual = Integer.parseInt(lblRetirarAF.getText());
        if ( cantActual > 0) {
            lblRetirarAF.setText(String.valueOf(cantActual - 1000));       
        }else {
            JOptionPane.showMessageDialog(this, "No se puede disminuir la cantidad a numeros negativos, recuerda que para retirar dinero debe ser positivo.", "NO SE ACEPTA CANTIDADES NEGATIVAS", HEIGHT);
        }


    }//GEN-LAST:event_btnRetirarRestaActionPerformed

    private void btnRetirarSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarSumaActionPerformed
        int cantActualRetirar = Integer.parseInt(lblRetirarAF.getText());
        double cantActual = Double.parseDouble(lblDineroAhorrosFijos.getText());
        if(cantActualRetirar < cantActual){
            lblRetirarAF.setText(String.valueOf(cantActualRetirar + 1000)); 
        }else{
            JOptionPane.showMessageDialog(this, "No se puede retirar una cantidad mayor a la que hay disponible en el bolsillo", "DINERO INSUFICIENTE PARA RETIRAR", HEIGHT);
        } 

    }//GEN-LAST:event_btnRetirarSumaActionPerformed

    private void bntRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRetirarActionPerformed
        int cantActualRetirar = Integer.parseInt(lblRetirarAF.getText());
        double cantActual = Double.parseDouble(lblDineroAhorrosFijos.getText());
        
        if (cantActualRetirar >= 0) {
            if(cantActualRetirar <= cantActual){
                cantActual -= cantActualRetirar;
                lblDineroAhorrosFijos.setText(String.valueOf(cantActual));
                user.ahorroFijo.retirarCantidad(cantActualRetirar, cantActual);
                lblRetirarAF.setText("0");
            }else{
                JOptionPane.showMessageDialog(this, "No se puede retirar una cantidad mayor a la disponible, por favor verifique la cantidad a retirar", "NO SE PUEDE RETIRAR", HEIGHT);
            }  
        }else{
            JOptionPane.showMessageDialog(this, "No se puede retirar 0 a la cantidad, por favor verifique la cantidad a retirar", "NO SE PUEDE RETIRAR 0", HEIGHT);
        }
    }//GEN-LAST:event_bntRetirarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

        int cantActualAgregar = Integer.parseInt(lblAgregarAF.getText());
        double cantActual = Double.parseDouble(lblDineroAhorrosFijos.getText());

        if (cantActualAgregar > 0) {

            cantActual += cantActualAgregar;
            lblDineroAhorrosFijos.setText(String.valueOf(cantActual));
            user.ahorroFijo.agregarCantidad(cantActualAgregar, cantActual);
            lblAgregarAF.setText("0");
        }else{
            JOptionPane.showMessageDialog(this, "No se puede agregar 0 a la cantidad, por favor verifique la cantidad a agregar", "NO SE PUEDE AGREGAR 0", HEIGHT);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void pnlAtrasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAtrasMousePressed
        FrmPrincipal principal = new FrmPrincipal();
        principal.setVisible(true);
        this.setVisible(false); //Modificamos la visibilidad de este JFrame para no estar abriendo tantas ventanas.

        user.ahorroFijo.setDescripcion(txtDescripcionAF.getText());
        user.ahorroFijo.cantidadTotal = 0;
        user.ahorroFijo.cantidadTotal = Double.parseDouble(lblDineroAhorrosFijos.getText());
        
    }//GEN-LAST:event_pnlAtrasMousePressed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntRetirar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAgregarResta;
    private javax.swing.JButton btnAgregarSuma;
    private javax.swing.JButton btnRetirarResta;
    private javax.swing.JButton btnRetirarSuma;
    private javax.swing.JLabel iconLogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAgregarAF;
    private javax.swing.JLabel lblDineroAhorrosFijos;
    private javax.swing.JLabel lblRetirarAF;
    private javax.swing.JPanel pnlAtras;
    private javax.swing.JTextPane txtDescripcionAF;
    // End of variables declaration//GEN-END:variables
}
