/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.safemoney.gui;

import static com.safemoney.gui.IniciarSesion.user;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author JOHANNA
 */
public class frmGastosHormiga extends javax.swing.JFrame {



    //Capturamos la ruta donde se encuentra la imagen que queremos colocar como icono del JFrame.
    public final String ruta = "/com/safemoney/imagenes/logo.png";
    /**
     * Creates new form frmAhorrosFijos
     */
    public frmGastosHormiga() {
        initComponents();
        this.setLocationRelativeTo(null);
        //Capturar imagen con ayuda de un toolkit que recupera una imagen 
        Image icono = Toolkit.getDefaultToolkit().getImage(getClass().getResource(ruta));
        //Mostrar imagen en el icono del JFrame
        setIconImage(icono);
        
        lblDineroGastosHormiga.setText(String.valueOf(user.gastosHormiga.getCantidad()));
        txtDescripcionGH.setText(user.gastosHormiga.getDescripcion());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblAgregarGH = new javax.swing.JLabel();
        btnAgregarSumaGH = new javax.swing.JButton();
        btnAgregarRestaGH = new javax.swing.JButton();
        btnAgregarGH = new javax.swing.JButton();
        lblRetirarGH = new javax.swing.JLabel();
        btnRetirarRestaGH = new javax.swing.JButton();
        btnRetirarSumaGH = new javax.swing.JButton();
        btnRetirarGH = new javax.swing.JButton();
        iconLogo = new javax.swing.JLabel();
        lblDineroGastosHormiga = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDescripcionGH = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pnlAtras = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 0, 204));
        setSize(new java.awt.Dimension(1536, 864));

        jPanel1.setBackground(new java.awt.Color(102, 0, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAgregarGH.setFont(new java.awt.Font("Open Sans", 0, 48)); // NOI18N
        lblAgregarGH.setForeground(new java.awt.Color(255, 255, 255));
        lblAgregarGH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAgregarGH.setText("0");
        jPanel1.add(lblAgregarGH, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 340, 320, 50));

        btnAgregarSumaGH.setFont(new java.awt.Font("Chewy", 0, 24)); // NOI18N
        btnAgregarSumaGH.setText("+");
        btnAgregarSumaGH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarSumaGHActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarSumaGH, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 340, 70, 50));

        btnAgregarRestaGH.setFont(new java.awt.Font("Chewy", 0, 24)); // NOI18N
        btnAgregarRestaGH.setText("-");
        btnAgregarRestaGH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarRestaGHActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarRestaGH, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 340, 70, 50));

        btnAgregarGH.setFont(new java.awt.Font("Chewy", 0, 24)); // NOI18N
        btnAgregarGH.setText("Agregar");
        btnAgregarGH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarGHActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarGH, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 430, 170, 40));

        lblRetirarGH.setFont(new java.awt.Font("Open Sans", 0, 48)); // NOI18N
        lblRetirarGH.setForeground(new java.awt.Color(255, 255, 255));
        lblRetirarGH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRetirarGH.setText("0");
        jPanel1.add(lblRetirarGH, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 550, 320, 50));

        btnRetirarRestaGH.setFont(new java.awt.Font("Chewy", 0, 24)); // NOI18N
        btnRetirarRestaGH.setText("-");
        btnRetirarRestaGH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarRestaGHActionPerformed(evt);
            }
        });
        jPanel1.add(btnRetirarRestaGH, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 550, 70, 50));

        btnRetirarSumaGH.setFont(new java.awt.Font("Chewy", 0, 24)); // NOI18N
        btnRetirarSumaGH.setText("+");
        btnRetirarSumaGH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarSumaGHActionPerformed(evt);
            }
        });
        jPanel1.add(btnRetirarSumaGH, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 550, 70, 50));

        btnRetirarGH.setFont(new java.awt.Font("Chewy", 0, 24)); // NOI18N
        btnRetirarGH.setText("Retirar");
        btnRetirarGH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarGHActionPerformed(evt);
            }
        });
        jPanel1.add(btnRetirarGH, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 640, 170, 40));

        iconLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/safemoney/imagenes/alcanciaCerditoPrincipal.png"))); // NOI18N
        jPanel1.add(iconLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, 420, 400));

        lblDineroGastosHormiga.setFont(new java.awt.Font("Chewy", 0, 48)); // NOI18N
        lblDineroGastosHormiga.setForeground(new java.awt.Color(255, 255, 255));
        lblDineroGastosHormiga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDineroGastosHormiga.setText("0");
        jPanel1.add(lblDineroGastosHormiga, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 190, 400, 40));

        txtDescripcionGH.setFont(new java.awt.Font("Open Sans", 0, 24)); // NOI18N
        jScrollPane3.setViewportView(txtDescripcionGH);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 430, 380));

        jLabel2.setBackground(new java.awt.Color(0, 204, 255));
        jLabel2.setFont(new java.awt.Font("Chewy", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Descripción");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 170, 50));

        jLabel4.setBackground(new java.awt.Color(0, 204, 255));
        jLabel4.setFont(new java.awt.Font("Chewy", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Cantidad");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 140, 150, 30));

        jLabel5.setBackground(new java.awt.Color(0, 204, 255));
        jLabel5.setFont(new java.awt.Font("Chewy", 0, 50)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/safemoney/imagenes/hormigaIcono.png"))); // NOI18N
        jLabel5.setText("GASTOS HORMIGA");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 590, 180));

        pnlAtras.setBackground(new java.awt.Color(255, 58, 58));
        pnlAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlAtrasMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Chewy", 0, 80)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("<-");

        javax.swing.GroupLayout pnlAtrasLayout = new javax.swing.GroupLayout(pnlAtras);
        pnlAtras.setLayout(pnlAtrasLayout);
        pnlAtrasLayout.setHorizontalGroup(
            pnlAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAtrasLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        pnlAtrasLayout.setVerticalGroup(
            pnlAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAtrasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel1.add(pnlAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1529, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 864, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarSumaGHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarSumaGHActionPerformed
        int cantActual = Integer.parseInt(lblAgregarGH.getText());
        lblAgregarGH.setText(String.valueOf(cantActual + 1000));
    }//GEN-LAST:event_btnAgregarSumaGHActionPerformed

    private void btnAgregarRestaGHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarRestaGHActionPerformed
        int cantActual = Integer.parseInt(lblAgregarGH.getText());

        if ( cantActual > 0) {
            lblAgregarGH.setText(String.valueOf(cantActual - 1000));
        } else {
            JOptionPane.showMessageDialog(this, "No se puede disminuir la cantidad a numeros negativos, recuerda que para agregar dinero debe ser positivo.", "NO SE ACEPTA CANTIDADES NEGATIVAS", HEIGHT);
        }
    }//GEN-LAST:event_btnAgregarRestaGHActionPerformed

    private void btnAgregarGHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarGHActionPerformed
        int cantActualAgregar = Integer.parseInt(lblAgregarGH.getText());
        double cantActual = Double.parseDouble(lblDineroGastosHormiga.getText());

        if (cantActualAgregar > 0) {

            cantActual += cantActualAgregar;
            lblDineroGastosHormiga.setText(String.valueOf(cantActual));
            user.gastosHormiga.agregarCantidad(cantActualAgregar, cantActual);
            
            lblAgregarGH.setText("0");
        }else{
            JOptionPane.showMessageDialog(this, "No se puede agregar 0 a la cantidad, por favor verifique la cantidad a agregar", "NO SE PUEDE AGREGAR 0", HEIGHT);
        }
    }//GEN-LAST:event_btnAgregarGHActionPerformed

    private void btnRetirarSumaGHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarSumaGHActionPerformed
        int cantActualRetirar = Integer.parseInt(lblRetirarGH.getText());
        double cantActual = Double.parseDouble(lblDineroGastosHormiga.getText());
        if(cantActualRetirar < cantActual){
            lblRetirarGH.setText(String.valueOf(cantActualRetirar + 1000));
        }else{
            JOptionPane.showMessageDialog(this, "No se puede retirar una cantidad mayor a la que hay disponible en el bolsillo", "DINERO INSUFICIENTE PARA RETIRAR", HEIGHT);
        }
    }//GEN-LAST:event_btnRetirarSumaGHActionPerformed

    private void btnRetirarRestaGHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarRestaGHActionPerformed
        int cantActual = Integer.parseInt(lblRetirarGH.getText());
        if ( cantActual > 0) {
            lblRetirarGH.setText(String.valueOf(cantActual - 1000));
        }else {
            JOptionPane.showMessageDialog(this, "No se puede disminuir la cantidad a numeros negativos, recuerda que para retirar dinero debe ser positivo.", "NO SE ACEPTA CANTIDADES NEGATIVAS", HEIGHT);
        }
    }//GEN-LAST:event_btnRetirarRestaGHActionPerformed

    private void btnRetirarGHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarGHActionPerformed
        int cantActualRetirar = Integer.parseInt(lblRetirarGH.getText());
        double cantActual = Double.parseDouble(lblDineroGastosHormiga.getText());

        if (cantActualRetirar >= 0) {
            if(cantActualRetirar <= cantActual){
                cantActual -= cantActualRetirar;
                lblDineroGastosHormiga.setText(String.valueOf(cantActual));
                user.gastosHormiga.retirarCantidad(cantActualRetirar, cantActual);
                lblRetirarGH.setText("0");
            }else{
                JOptionPane.showMessageDialog(this, "No se puede retirar una cantidad mayor a la disponible, por favor verifique la cantidad a retirar", "NO SE PUEDE RETIRAR", HEIGHT);
            }
        }else{
            JOptionPane.showMessageDialog(this, "No se puede retirar 0 a la cantidad, por favor verifique la cantidad a retirar", "NO SE PUEDE RETIRAR 0", HEIGHT);
        }
    }//GEN-LAST:event_btnRetirarGHActionPerformed

    private void pnlAtrasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAtrasMousePressed
        FrmPrincipal principal = new FrmPrincipal();
        principal.setVisible(true);
        this.setVisible(false); //Modificamos la visibilidad de este JFrame para no estar abriendo tantas ventanas.

        user.gastosHormiga.setDescripcion(txtDescripcionGH.getText());
        user.gastosHormiga.cantidadTotal = 0;
        user.gastosHormiga.cantidadTotal = Double.parseDouble(lblDineroGastosHormiga.getText());

    }//GEN-LAST:event_pnlAtrasMousePressed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarGH;
    private javax.swing.JButton btnAgregarRestaGH;
    private javax.swing.JButton btnAgregarSumaGH;
    private javax.swing.JButton btnRetirarGH;
    private javax.swing.JButton btnRetirarRestaGH;
    private javax.swing.JButton btnRetirarSumaGH;
    private javax.swing.JLabel iconLogo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAgregarGH;
    private javax.swing.JLabel lblDineroGastosHormiga;
    private javax.swing.JLabel lblRetirarGH;
    private javax.swing.JPanel pnlAtras;
    private javax.swing.JTextPane txtDescripcionGH;
    // End of variables declaration//GEN-END:variables
}
