
package com.safemoney.gui;
import static com.safemoney.gui.IniciarSesion.user;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;


public class frmGastosFijos extends javax.swing.JFrame {
    
    //Capturamos la ruta donde se encuentra la imagen que queremos colocar como icono del JFrame.
    public final String ruta = "/com/safemoney/imagenes/alcanciaCerditoPrincipal.png";
    
    /**
     * Creates new form frmAhorrosFijos
     */
    public frmGastosFijos() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        lblDineroGastosFijos.setText(String.valueOf(user.gastosFijos.getCantidad()));
        txtDescripcionGF.setText(user.gastosFijos.getDescripcion());
        
        //Capturar imagen con ayuda de un toolkit que recupera una imagen 
        Image icono = Toolkit.getDefaultToolkit().getImage(getClass().getResource(ruta));
        //Mostrar imagen en el icono del JFrame
        setIconImage(icono);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblRetirarGF = new javax.swing.JLabel();
        btnRetirarRestaGF = new javax.swing.JButton();
        btnRetirarSumaGF = new javax.swing.JButton();
        btnAceptarRetirarGF = new javax.swing.JButton();
        lblAgregarGF = new javax.swing.JLabel();
        btnAgregarSumaGF = new javax.swing.JButton();
        btnAgregarRestaGF = new javax.swing.JButton();
        btnAgregarGF = new javax.swing.JButton();
        iconLogo = new javax.swing.JLabel();
        lblDineroGastosFijos = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDescripcionGF = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pnlAtras = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 0, 204));

        jPanel1.setBackground(new java.awt.Color(102, 0, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRetirarGF.setFont(new java.awt.Font("Open Sans", 0, 48)); // NOI18N
        lblRetirarGF.setForeground(new java.awt.Color(255, 255, 255));
        lblRetirarGF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRetirarGF.setText("0");
        jPanel1.add(lblRetirarGF, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 530, 300, 50));

        btnRetirarRestaGF.setFont(new java.awt.Font("Chewy", 0, 24)); // NOI18N
        btnRetirarRestaGF.setText("-");
        btnRetirarRestaGF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarRestaGFActionPerformed(evt);
            }
        });
        jPanel1.add(btnRetirarRestaGF, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 530, 70, 50));

        btnRetirarSumaGF.setFont(new java.awt.Font("Chewy", 0, 24)); // NOI18N
        btnRetirarSumaGF.setText("+");
        btnRetirarSumaGF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarSumaGFActionPerformed(evt);
            }
        });
        jPanel1.add(btnRetirarSumaGF, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 530, 70, 50));

        btnAceptarRetirarGF.setFont(new java.awt.Font("Chewy", 0, 24)); // NOI18N
        btnAceptarRetirarGF.setText("Retirar");
        btnAceptarRetirarGF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarRetirarGFActionPerformed(evt);
            }
        });
        jPanel1.add(btnAceptarRetirarGF, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 600, 170, 40));

        lblAgregarGF.setFont(new java.awt.Font("Open Sans", 0, 48)); // NOI18N
        lblAgregarGF.setForeground(new java.awt.Color(255, 255, 255));
        lblAgregarGF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAgregarGF.setText("0");
        jPanel1.add(lblAgregarGF, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 300, 50));

        btnAgregarSumaGF.setFont(new java.awt.Font("Chewy", 0, 24)); // NOI18N
        btnAgregarSumaGF.setText("+");
        btnAgregarSumaGF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarSumaGFActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarSumaGF, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, 70, 50));

        btnAgregarRestaGF.setFont(new java.awt.Font("Chewy", 0, 24)); // NOI18N
        btnAgregarRestaGF.setText("-");
        btnAgregarRestaGF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarRestaGFActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarRestaGF, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 70, 50));

        btnAgregarGF.setFont(new java.awt.Font("Chewy", 0, 24)); // NOI18N
        btnAgregarGF.setText("Agregar");
        btnAgregarGF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarGFActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarGF, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 170, 40));

        iconLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/safemoney/imagenes/alcanciaCerditoPrincipalAlReves.png"))); // NOI18N
        jPanel1.add(iconLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 417, -1));

        lblDineroGastosFijos.setFont(new java.awt.Font("Chewy", 0, 48)); // NOI18N
        lblDineroGastosFijos.setForeground(new java.awt.Color(255, 255, 255));
        lblDineroGastosFijos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDineroGastosFijos.setText("0");
        jPanel1.add(lblDineroGastosFijos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 300, 40));

        txtDescripcionGF.setFont(new java.awt.Font("Open Sans", 0, 24)); // NOI18N
        jScrollPane3.setViewportView(txtDescripcionGF);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 330, 410, 320));

        jLabel2.setBackground(new java.awt.Color(0, 204, 255));
        jLabel2.setFont(new java.awt.Font("Chewy", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Descripción");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 260, 220, 50));

        jLabel3.setBackground(new java.awt.Color(0, 204, 255));
        jLabel3.setFont(new java.awt.Font("Chewy", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Cantidad");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 150, 30));

        pnlAtras.setBackground(new java.awt.Color(255, 58, 58));
        pnlAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlAtrasMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Chewy", 0, 80)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("<-");

        javax.swing.GroupLayout pnlAtrasLayout = new javax.swing.GroupLayout(pnlAtras);
        pnlAtras.setLayout(pnlAtrasLayout);
        pnlAtrasLayout.setHorizontalGroup(
            pnlAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAtrasLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAtrasLayout.setVerticalGroup(
            pnlAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAtrasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(pnlAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        jLabel5.setBackground(new java.awt.Color(0, 204, 255));
        jLabel5.setFont(new java.awt.Font("Chewy", 0, 50)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/safemoney/imagenes/bolsaDinero.png"))); // NOI18N
        jLabel5.setText("GASTOS FIJOS");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 70, 590, 180));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1529, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 864, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarRestaGFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarRestaGFActionPerformed
        int cantActual = Integer.parseInt(lblAgregarGF.getText());

        if ( cantActual > 0) {
            lblAgregarGF.setText(String.valueOf(cantActual - 1000));
        } else {
            JOptionPane.showMessageDialog(this, "No se puede disminuir la cantidad a numeros negativos, recuerda que para agregar dinero debe ser positivo.", "NO SE ACEPTA CANTIDADES NEGATIVAS", HEIGHT);
        }
    }//GEN-LAST:event_btnAgregarRestaGFActionPerformed

    private void btnAgregarSumaGFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarSumaGFActionPerformed
        int cantActual = Integer.parseInt(lblAgregarGF.getText());
        lblAgregarGF.setText(String.valueOf(cantActual + 1000));
    }//GEN-LAST:event_btnAgregarSumaGFActionPerformed

    private void btnRetirarRestaGFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarRestaGFActionPerformed
        int cantActual = Integer.parseInt(lblRetirarGF.getText());
        if ( cantActual > 0) {
            lblRetirarGF.setText(String.valueOf(cantActual - 1000));
        }else {
            JOptionPane.showMessageDialog(this, "No se puede disminuir la cantidad a numeros negativos, recuerda que para retirar dinero debe ser positivo.", "NO SE ACEPTA CANTIDADES NEGATIVAS", HEIGHT);
        }
    }//GEN-LAST:event_btnRetirarRestaGFActionPerformed

    private void btnRetirarSumaGFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarSumaGFActionPerformed
        int cantActualRetirar = Integer.parseInt(lblRetirarGF.getText());
        double cantActual = Double.parseDouble(lblDineroGastosFijos.getText());
        
        if(cantActualRetirar < cantActual){
            lblRetirarGF.setText(String.valueOf(cantActualRetirar + 1000));
        }else{
            JOptionPane.showMessageDialog(this, "No se puede retirar una cantidad mayor a la que hay disponible en el bolsillo", "DINERO INSUFICIENTE PARA RETIRAR", HEIGHT);
        }
    }//GEN-LAST:event_btnRetirarSumaGFActionPerformed

    private void btnAgregarGFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarGFActionPerformed
        int cantActualAgregar = Integer.parseInt(lblAgregarGF.getText());
        double cantActual = Double.parseDouble(lblDineroGastosFijos.getText());

        if (cantActualAgregar > 0) {

            cantActual += cantActualAgregar;
            lblDineroGastosFijos.setText(String.valueOf(cantActual));
            user.gastosFijos.agregarCantidad(cantActualAgregar, cantActual);
            
            lblAgregarGF.setText("0");
        }else{
            JOptionPane.showMessageDialog(this, "No se puede agregar 0 a la cantidad, por favor verifique la cantidad a agregar", "NO SE PUEDE AGREGAR 0", HEIGHT);
        }
    }//GEN-LAST:event_btnAgregarGFActionPerformed

    private void btnAceptarRetirarGFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarRetirarGFActionPerformed
        int cantActualRetirar = Integer.parseInt(lblRetirarGF.getText());
        double cantActual = Double.parseDouble(lblDineroGastosFijos.getText());

        if (cantActualRetirar >= 0) {
            if(cantActualRetirar <= cantActual){
                cantActual -= cantActualRetirar;
                lblDineroGastosFijos.setText(String.valueOf(cantActual));
                user.gastosFijos.retirarCantidad(cantActualRetirar, cantActual);
                lblRetirarGF.setText("0");
            }else{
                JOptionPane.showMessageDialog(this, "No se puede retirar una cantidad mayor a la disponible, por favor verifique la cantidad a retirar", "NO SE PUEDE RETIRAR", HEIGHT);
            }
        }else{
            JOptionPane.showMessageDialog(this, "No se puede retirar 0 a la cantidad, por favor verifique la cantidad a retirar", "NO SE PUEDE RETIRAR 0", HEIGHT);
        }

    }//GEN-LAST:event_btnAceptarRetirarGFActionPerformed

    private void pnlAtrasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAtrasMousePressed
        FrmPrincipal principal = new FrmPrincipal();
        principal.setVisible(true);
        this.setVisible(false); //Modificamos la visibilidad de este JFrame para no estar abriendo tantas ventanas.

        user.gastosFijos.setDescripcion(txtDescripcionGF.getText());
        user.gastosFijos.cantidadTotal = 0;
        user.gastosFijos.cantidadTotal = Double.parseDouble(lblDineroGastosFijos.getText());
    }//GEN-LAST:event_pnlAtrasMousePressed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarRetirarGF;
    private javax.swing.JButton btnAgregarGF;
    private javax.swing.JButton btnAgregarRestaGF;
    private javax.swing.JButton btnAgregarSumaGF;
    private javax.swing.JButton btnRetirarRestaGF;
    private javax.swing.JButton btnRetirarSumaGF;
    private javax.swing.JLabel iconLogo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAgregarGF;
    private javax.swing.JLabel lblDineroGastosFijos;
    private javax.swing.JLabel lblRetirarGF;
    private javax.swing.JPanel pnlAtras;
    private javax.swing.JTextPane txtDescripcionGF;
    // End of variables declaration//GEN-END:variables
}
