/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.safemoney.gui;

import static com.safemoney.gui.IniciarSesion.user;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author wilsa
 */
public class FrmPrincipal extends javax.swing.JFrame {
    
    //Capturamos la ruta donde se encuentra la imagen que queremos colocar como icono del JFrame
    public final String ruta = "/com/safemoney/imagenes/logo.png";
    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {

        initComponents();
        this.setLocationRelativeTo(null);
        //Capturar imagen con ayuda de un toolkit que recupera una imagen 
        Image icono = Toolkit.getDefaultToolkit().getImage(getClass().getResource(ruta));
        //Mostrar imagen en el icono del JFrame
        setIconImage(icono);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnServicios = new javax.swing.JButton();
        btnUsuario = new javax.swing.JButton();
        lblDineroTotal = new javax.swing.JLabel();
        btnGastosHormiga = new javax.swing.JButton();
        btnAhorrosFijos = new javax.swing.JButton();
        btnGastosFijos = new javax.swing.JButton();
        iconLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1536, 864));

        jPanel1.setBackground(new java.awt.Color(132, 97, 244));
        jPanel1.setLayout(null);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/safemoney/imagenes/Flecha.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(620, 660, 90, 80);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/safemoney/imagenes/Flecha.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(620, 480, 90, 80);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/safemoney/imagenes/Flecha.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(620, 110, 90, 80);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/safemoney/imagenes/Flecha.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(620, 290, 90, 80);

        btnServicios.setBackground(new java.awt.Color(0, 204, 255));
        btnServicios.setFont(new java.awt.Font("Chewy", 0, 48)); // NOI18N
        btnServicios.setForeground(new java.awt.Color(255, 255, 255));
        btnServicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/safemoney/imagenes/bombilloServicios.png"))); // NOI18N
        btnServicios.setText("     SERVICIOS");
        btnServicios.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServiciosActionPerformed(evt);
            }
        });
        jPanel1.add(btnServicios);
        btnServicios.setBounds(80, 250, 660, 170);

        btnUsuario.setBackground(new java.awt.Color(102, 160, 255));
        btnUsuario.setFont(new java.awt.Font("Chewy", 0, 46)); // NOI18N
        btnUsuario.setForeground(new java.awt.Color(101, 204, 255));
        btnUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/safemoney/imagenes/iconUser1.png"))); // NOI18N
        btnUsuario.setText("Usuario");
        btnUsuario.setBorderPainted(false);
        btnUsuario.setContentAreaFilled(false);
        btnUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(btnUsuario);
        btnUsuario.setBounds(1250, 20, 270, 60);

        lblDineroTotal.setBackground(new java.awt.Color(0, 204, 255));
        lblDineroTotal.setFont(new java.awt.Font("Chewy", 1, 48)); // NOI18N
        lblDineroTotal.setForeground(new java.awt.Color(0, 204, 255));
        lblDineroTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDineroTotal.setText("0");
        lblDineroTotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblDineroTotalMousePressed(evt);
            }
        });
        jPanel1.add(lblDineroTotal);
        lblDineroTotal.setBounds(900, 580, 480, 70);

        btnGastosHormiga.setBackground(new java.awt.Color(0, 204, 255));
        btnGastosHormiga.setFont(new java.awt.Font("Chewy", 0, 48)); // NOI18N
        btnGastosHormiga.setForeground(new java.awt.Color(255, 255, 255));
        btnGastosHormiga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/safemoney/imagenes/hormigaIcono.png"))); // NOI18N
        btnGastosHormiga.setText("GASTOS HORMIGA");
        btnGastosHormiga.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnGastosHormiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGastosHormigaActionPerformed(evt);
            }
        });
        jPanel1.add(btnGastosHormiga);
        btnGastosHormiga.setBounds(80, 430, 660, 170);

        btnAhorrosFijos.setBackground(new java.awt.Color(0, 204, 255));
        btnAhorrosFijos.setFont(new java.awt.Font("Chewy", 0, 48)); // NOI18N
        btnAhorrosFijos.setForeground(new java.awt.Color(255, 255, 255));
        btnAhorrosFijos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/safemoney/imagenes/ImagenAhorrosFijos.png"))); // NOI18N
        btnAhorrosFijos.setText("     AHORROS FIJOS");
        btnAhorrosFijos.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnAhorrosFijos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAhorrosFijosActionPerformed(evt);
            }
        });
        jPanel1.add(btnAhorrosFijos);
        btnAhorrosFijos.setBounds(80, 70, 660, 170);

        btnGastosFijos.setBackground(new java.awt.Color(0, 204, 255));
        btnGastosFijos.setFont(new java.awt.Font("Chewy", 0, 48)); // NOI18N
        btnGastosFijos.setForeground(new java.awt.Color(255, 255, 255));
        btnGastosFijos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/safemoney/imagenes/bolsaDinero.png"))); // NOI18N
        btnGastosFijos.setText("    GASTOS FIJOS");
        btnGastosFijos.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnGastosFijos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGastosFijosActionPerformed(evt);
            }
        });
        jPanel1.add(btnGastosFijos);
        btnGastosFijos.setBounds(80, 610, 660, 170);

        iconLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/safemoney/imagenes/alcanciaCerditoPrincipal.png"))); // NOI18N
        jPanel1.add(iconLogo);
        iconLogo.setBounds(920, 90, 430, 430);

        jLabel1.setBackground(new java.awt.Color(0, 204, 255));
        jLabel1.setFont(new java.awt.Font("Chewy", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 255));
        jLabel1.setText("Su dinero Total");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(1000, 530, 280, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1536, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 864, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /*
    * Este método se ejecuta al hacer click en el botón usuario dentro de la pantalla principal
    */
    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed

        frmUsuario usuario = new frmUsuario(); //Instanciamos un nuevo objeto de tipo FrmUsuario (otra pantalla donde está toda la información del usuario que ingresó)
        usuario.setVisible(true); //Cambiamos la visibilidad para que se muestre.
        this.setVisible(false); //Modificamos la visibilidad de la ventana donde estamos para que se oculte.

    }//GEN-LAST:event_btnUsuarioActionPerformed

    private void btnAhorrosFijosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAhorrosFijosActionPerformed
        frmAhorrosFijos aFijos = new frmAhorrosFijos();
        aFijos.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btnAhorrosFijosActionPerformed

    private void btnServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServiciosActionPerformed
        frmServicios serv = new frmServicios();
        serv.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnServiciosActionPerformed

    private void btnGastosHormigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGastosHormigaActionPerformed
        frmGastosHormiga gastosH = new frmGastosHormiga();
        gastosH.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btnGastosHormigaActionPerformed

    private void btnGastosFijosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGastosFijosActionPerformed

        frmGastosFijos gastosF = new frmGastosFijos();
        gastosF.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnGastosFijosActionPerformed

    private void lblDineroTotalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDineroTotalMousePressed
        double cantAhorro = user.ahorroFijo.getCantidad();
        double cantServicios = user.servicio.getCantidad();
        double cantGastosHormiga = user.gastosHormiga.getCantidad();
        double cantGastosFijos = user.gastosFijos.getCantidad();
        
        
        double totalDinero = cantAhorro + cantServicios + cantGastosHormiga + cantGastosFijos;
        
        lblDineroTotal.setText(String.valueOf(totalDinero));
        
    }//GEN-LAST:event_lblDineroTotalMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAhorrosFijos;
    private javax.swing.JButton btnGastosFijos;
    private javax.swing.JButton btnGastosHormiga;
    private javax.swing.JButton btnServicios;
    private javax.swing.JButton btnUsuario;
    private javax.swing.JLabel iconLogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDineroTotal;
    // End of variables declaration//GEN-END:variables
}
