/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.safemoney.gui;

import com.safemoney.clases.Usuario;
import static com.safemoney.gui.IniciarSesion.usuarios;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author wilsa
 */
public class FrmRegistro extends javax.swing.JFrame {

    /**
     * Creates new form FrmRegistro
    */
    
    /*
    * @Wilson cree una variable de tipo Usuario donde almacenaremos el nuevo usuario dentro del ArrayList mas adelante, la declaramos como variable
    * global para acceder a este Usuario en diferentes métodos.
    */
    private Usuario user;
    
    /*
    * Esta variable nos ayuda a contar los usuarios que se van registrando y asi mismo asignando una clave unica a cada usuario para asi distinguir
    * entre estos y hallar el usuario cuando se necesite.
    */
    public static int cantUsuarios = 0;  
    
    
    public FrmRegistro() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        //Instanciamos una nueva ventana para utilizar la variable de ruta y asi mostrar el icono correspondiente
        IniciarSesion login = new IniciarSesion();
        
        //Capturar imagen con ayuda de un toolkit que recupera una imagen dependiendo de una ruta que se trae con ayudaed la nueva instancia
        Image icono = Toolkit.getDefaultToolkit().getImage(getClass().getResource(login.ruta));
        //Modificar la imagen por defecto en el icono del JFrame, con ayuda de la imagen que buscamos anteriormente.
        setIconImage(icono);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        backgroundDecoracion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tituloRegistro = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblCorreo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        lblEdad = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        lblContraseña = new javax.swing.JLabel();
        mostrarPass = new javax.swing.JToggleButton();
        passContraseña = new javax.swing.JPasswordField();
        btnRegistrar = new javax.swing.JButton();
        btnIniciarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Safe Money $$$");
        setSize(new java.awt.Dimension(1536, 864));

        background.setBackground(new java.awt.Color(56, 182, 255));
        background.setName(""); // NOI18N
        background.setLayout(null);

        backgroundDecoracion.setBackground(new java.awt.Color(189, 231, 255));
        backgroundDecoracion.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/safemoney/imagenes/imagenTrabajador.png"))); // NOI18N
        backgroundDecoracion.add(jLabel1);
        jLabel1.setBounds(0, 10, 540, 870);

        background.add(backgroundDecoracion);
        backgroundDecoracion.setBounds(896, 0, 640, 864);

        tituloRegistro.setFont(new java.awt.Font("Chewy", 0, 92)); // NOI18N
        tituloRegistro.setForeground(new java.awt.Color(222, 242, 255));
        tituloRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloRegistro.setText("Registrarse");
        background.add(tituloRegistro);
        tituloRegistro.setBounds(250, 30, 430, 120);

        lblNombre.setFont(new java.awt.Font("Chewy", 0, 46)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(222, 242, 255));
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombre.setText("Nombre:");
        background.add(lblNombre);
        lblNombre.setBounds(40, 220, 230, 50);

        txtNombre.setBackground(new java.awt.Color(242, 250, 255));
        txtNombre.setFont(new java.awt.Font("Open Sans", 0, 19)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(180, 180, 180));
        txtNombre.setText("Ingrese su nombre");
        txtNombre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(189, 231, 255), 1, true));
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreMousePressed(evt);
            }
        });
        background.add(txtNombre);
        txtNombre.setBounds(310, 230, 490, 40);

        lblCorreo.setFont(new java.awt.Font("Chewy", 0, 46)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(222, 242, 255));
        lblCorreo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCorreo.setText("Correo:");
        background.add(lblCorreo);
        lblCorreo.setBounds(40, 380, 230, 50);

        txtCorreo.setBackground(new java.awt.Color(242, 250, 255));
        txtCorreo.setFont(new java.awt.Font("Open Sans", 0, 19)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(180, 180, 180));
        txtCorreo.setText("Ingrese su correo electrónico");
        txtCorreo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(189, 231, 255), 1, true));
        txtCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCorreoMousePressed(evt);
            }
        });
        background.add(txtCorreo);
        txtCorreo.setBounds(310, 390, 490, 40);

        lblEdad.setFont(new java.awt.Font("Chewy", 0, 46)); // NOI18N
        lblEdad.setForeground(new java.awt.Color(222, 242, 255));
        lblEdad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEdad.setText("Edad:");
        background.add(lblEdad);
        lblEdad.setBounds(40, 300, 230, 50);

        txtEdad.setBackground(new java.awt.Color(242, 250, 255));
        txtEdad.setFont(new java.awt.Font("Open Sans", 0, 19)); // NOI18N
        txtEdad.setForeground(new java.awt.Color(180, 180, 180));
        txtEdad.setText("Ingrese su edad");
        txtEdad.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(189, 231, 255), 1, true));
        txtEdad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtEdadMousePressed(evt);
            }
        });
        background.add(txtEdad);
        txtEdad.setBounds(310, 310, 490, 40);

        lblContraseña.setFont(new java.awt.Font("Chewy", 0, 46)); // NOI18N
        lblContraseña.setForeground(new java.awt.Color(222, 242, 255));
        lblContraseña.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblContraseña.setText("Contraseña:");
        background.add(lblContraseña);
        lblContraseña.setBounds(40, 460, 230, 50);

        mostrarPass.setBackground(new java.awt.Color(158, 217, 255));
        mostrarPass.setForeground(new java.awt.Color(255, 255, 255));
        mostrarPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/safemoney/imagenes/ojoCerrado.png"))); // NOI18N
        mostrarPass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(189, 231, 255)));
        mostrarPass.setContentAreaFilled(false);
        mostrarPass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mostrarPass.setFocusPainted(false);
        mostrarPass.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                mostrarPassItemStateChanged(evt);
            }
        });
        mostrarPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarPassActionPerformed(evt);
            }
        });
        background.add(mostrarPass);
        mostrarPass.setBounds(760, 470, 40, 40);

        passContraseña.setBackground(new java.awt.Color(242, 250, 255));
        passContraseña.setFont(new java.awt.Font("Open Sans", 0, 19)); // NOI18N
        passContraseña.setForeground(new java.awt.Color(180, 180, 180));
        passContraseña.setText("************");
        passContraseña.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(189, 231, 255), 1, true));
        passContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passContraseñaMousePressed(evt);
            }
        });
        background.add(passContraseña);
        passContraseña.setBounds(310, 470, 490, 40);

        btnRegistrar.setBackground(new java.awt.Color(222, 242, 255));
        btnRegistrar.setFont(new java.awt.Font("Chewy", 0, 29)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(56, 182, 255));
        btnRegistrar.setText("Registrar");
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        background.add(btnRegistrar);
        btnRegistrar.setBounds(170, 630, 200, 90);

        btnIniciarSesion.setBackground(new java.awt.Color(222, 242, 255));
        btnIniciarSesion.setFont(new java.awt.Font("Chewy", 0, 29)); // NOI18N
        btnIniciarSesion.setForeground(new java.awt.Color(56, 182, 255));
        btnIniciarSesion.setText("Iniciar Sesión");
        btnIniciarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });
        background.add(btnIniciarSesion);
        btnIniciarSesion.setBounds(520, 630, 200, 90);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 1536, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 864, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /*
    * Método que se ejecuta al presionar con el mouse en el campo de Edad
    */
    private void txtEdadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEdadMousePressed
        
        if(txtEdad.getText().equals("Ingrese su edad")){// Verifica si el campo edad es igual a "Ingrese su edad".
            txtEdad.setText(""); //Modifique texto a vacio.
            txtEdad.setForeground(Color.BLACK); //Modifique el color de letra a Negro.
        }
        if(txtNombre.getText().isEmpty()){ //Verifica si el texto en nombre es vacio.
            txtNombre.setText("Ingrese su nombre"); //Modifique su texto a "Ingrese su nombre".
            txtNombre.setForeground(new java.awt.Color(180,180,180)); //Modifique el color de la letra a Gris claro.
        }
        if(txtCorreo.getText().isEmpty()){ //Verifica si el texto del correo es vacio.
            txtCorreo.setText("Ingrese su correo electrónico"); //Modifique el texto del correo a "Ingrese su correo electrónico".
            txtCorreo.setForeground(new java.awt.Color(180,180,180)); //Modifique el color de la letra de ese campo a gris claro.
        }
        if(String.valueOf(passContraseña.getPassword()).isEmpty()){ //Hace la conversion a String  de la contraseña y valida si el texto de la contraseña es vacio.
            passContraseña.setText("************"); //Modificar texto de la contraseña a *.
            passContraseña.setForeground(new java.awt.Color(180,180,180)); //Modifique el color de la letra de este campo a gris claro
        }
    }//GEN-LAST:event_txtEdadMousePressed
    /*
    * Método que se ejecuta al presionar con el mouse en el campo de Nombre
    */
    private void txtNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMousePressed
        if(txtNombre.getText().equals("Ingrese su nombre")){ //Verifica si el campo de nombre es igual a "Ingrese su nombre".
            txtNombre.setText(""); //Modifique el texto a vacio.
            txtNombre.setForeground(Color.BLACK); //Modifique el color de la letra a negro.
        }
        if(txtEdad.getText().isEmpty()){ //Verifica si el campo de edad está vacio.
            txtEdad.setText("Ingrese su edad"); //Modifica el texto a "Ingrese su edad".
            txtEdad.setForeground(new java.awt.Color(180,180,180)); //Modifica el color de las letras a gris claro.
        }
        if(txtCorreo.getText().isEmpty()){ //Verifica si el campo del correo es vacio.
            txtCorreo.setText("Ingrese su correo electrónico"); //Modifica el texto a "Ingrese su correo electrónico".
            txtCorreo.setForeground(new java.awt.Color(180,180,180)); //Modifica el color de las letras a gris claro
        }
        if(String.valueOf(passContraseña.getPassword()).isEmpty()){ //Hace la conversion de la contraseña tipo char[] a String y valida si el campo de la contrasseña esta vacio.
            passContraseña.setText("************"); //Modifica el texto a *.
            passContraseña.setForeground(new java.awt.Color(180,180,180)); //Modifica el color de la letra a gris claro.
        }
    }//GEN-LAST:event_txtNombreMousePressed
    /*
    * Método que se ejecuta al presionar con el mouse en el campo de correo
    */
    private void txtCorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoMousePressed
        if(txtNombre.getText().isEmpty()){ //Verifica si el campo nombre está vacio.
            txtNombre.setText("Ingrese su nombre"); //Modifica el nombre a "Ingrese su nombre"(texto por defecto).
            txtNombre.setForeground(new java.awt.Color(180,180,180)); //Modifica el color de la letra a gris claro.
        }
        if(txtEdad.getText().isEmpty()){ //Verifica si el campo edad está vacio.
            txtEdad.setText("Ingrese su edad"); //Modifica el nombre a "Ingrese su edad" (texto por defecto).
            txtEdad.setForeground(new java.awt.Color(180,180,180)); //Modifica el color de la letra a gris claro.
        }
        if(txtCorreo.getText().equals("Ingrese su correo electrónico")){ //Verifica si el correo es igual al texto por defecto "Ingrese su correo electrónico".
            txtCorreo.setText(""); //Modifica el campo del correo a vacio (para ingresar correo desde 0.
            txtCorreo.setForeground(Color.BLACK); //Modifica el color de la letra a negro.
        }
        if(String.valueOf(passContraseña.getPassword()).isEmpty()){ //Hace la conversion de la contraseña tipo char[] a String y valida si el campo de la contrasseña esta vacio.
            passContraseña.setText("************"); //Modifica el texto a *.
            passContraseña.setForeground(new java.awt.Color(180,180,180)); //Modifica el color de la letra a gris claro.
        }
    }//GEN-LAST:event_txtCorreoMousePressed
    /*
    * Método que se ejecuta al presionar con el mouse en el campo de contraseña
    */
    private void passContraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passContraseñaMousePressed
        if(String.valueOf(passContraseña.getPassword()).equals("************")){ //Realiza el parceo de char[] a String para evaluar la igualdad con * (texto por defecto);
            passContraseña.setText(""); //Modifica el texto de campo a vacio (para ingresar una nueva contraseña al campo)
            passContraseña.setForeground(Color.BLACK); //Modifica el color del texto a negro.
        }
        if(txtNombre.getText().isEmpty()){ //Verifica si el campo de nombre esta vacio.
            txtNombre.setText("Ingrese su nombre"); //Modifica el texto a "Ingrese su nombre" (Texto por defecto).
            txtNombre.setForeground(new java.awt.Color(180,180,180)); //Modifica el color del texto a gris claro.
        }
        if(txtEdad.getText().isEmpty()){ //Verifica si el campo de edad está vacio.
            txtEdad.setText("Ingrese su edad"); //Modifica el texto a "Ingrese su edad" (texto por defecto).
            txtEdad.setForeground(new java.awt.Color(180,180,180)); //Modifica el color del texto a gris claro.
        }
        if(txtCorreo.getText().isEmpty()){ //Verifica si el campo del correo está vacio.
            txtCorreo.setText("Ingrese su correo electrónico"); //Modifica el campo a "Ingrese su correo electrónico" (texto por defecto).
            txtCorreo.setForeground(new java.awt.Color(180,180,180)); //Modifica el color del texto a gris claro.
        }
    }//GEN-LAST:event_passContraseñaMousePressed
    /*
    * Método que se ejecuta para comprobar si el boton esta seleccionado o no
    */
    private void mostrarPassItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_mostrarPassItemStateChanged
        if(mostrarPass.isSelected()){ //Verifica si el botón de mostrarPass esta seleccionado
            mostrarPass.setBackground(new java.awt.Color(158,217,255)); //Modifica el color de fondo del botón.
        }
        else{
            mostrarPass.setBackground(new java.awt.Color(242,250,255)); //Modifica el color de fondo del botón.
        }
    }//GEN-LAST:event_mostrarPassItemStateChanged
    /*
    * Método que se ejecuta al presionar el boton de mostrar password (icono de ojo cerrado)
    */
    private void mostrarPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarPassActionPerformed
        if(mostrarPass.isSelected()){ //Verifica si el botón mostrar parrword está seleccionado
            mostrarPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/safemoney/imagenes/ojoAbierto.png"))); //Modifica el icono a una nueva imagen tipo icono de una ruta o url dentro del proyecto (ojo abierto).
            passContraseña.setEchoChar((char)0); //Al llamar el metodo setEchoChar((char)0) permite mostrar la contraseña reemplazando todos los caracteres a caracteres visibles dentro del campo.
        }else{
            mostrarPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/safemoney/imagenes/ojoCerrado.png"))); //Modifica el icono a una nueva imagen de tipo icono de una ruta existente de una ruta o url dentro del proyecto (ojo cerrado) (icono por defecto).
            passContraseña.setEchoChar('*'); //Al modificar los caracteres por * cada uno se oculta con ese caracter.
        }
    }//GEN-LAST:event_mostrarPassActionPerformed
    /*
    * Método que se ejecuta cuando se le da click al botón registrar en el FrmRegistro, permite registrar el usuario segun los campos digitados.
    */
    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        //El try catch permite intentar ejecutar el codigo y en caso de recibir una excepcion de tipo NumberFormatException, ocurre cuando se ingresa un tipo de dato diferente a la de un numero.
        try{
            //Validamos que si el nombre es igual al texto por defecto o la edad, o el correo o el parseo de la  contraseña (Es decir que no se ha ingresado ningun dato en los campos) 
            if(txtNombre.getText().equals("Ingrese su nombre") || txtEdad.getText().equals("Ingrese su edad") || txtCorreo.getText().equals("Ingrese su correo electrónico") || String.valueOf(passContraseña.getPassword()).equals("************")){
                JOptionPane.showMessageDialog(this, "Los campos de nombre, edad, correo o Contraseña están vacios", "CAMPOS VACIOS", HEIGHT); //Muestra una ventana emergente que muestre que no se ha digitado ningun dato.
            }else{ //En caso de que no suceda esto validamos algunos campos en especifico.
                if(txtNombre.getText().length()>= 3){ //Validamos que el nombre sea válido superando 3 caracteres en el nombre, ya que un nombre puede ser tan solo de tres caracteres o más
                    if(Integer.parseInt(txtEdad.getText()) >= 18){ //Parseamos el texto de la edad a entero permitiendo evaluar que la edad sea mayor o igual a 18. Ya que maneja dinero y requiere solo ingreso de personas mayores de edad.
                        if(txtCorreo.getText().contains("@") && txtCorreo.getText().length() >= 10){ //Valida que en cualquier parte del campo haya un @ para que el correo sea valido y que supere un limite de 10 caracteres.
                            if(String.valueOf(passContraseña.getPassword()).length() >= 8){ //Valida que la contraseña sea mayor o igual a 8 caracteres para tener una contraseña segura.
                                //Guardamos losdatos en la instancia que creamos en un principio mencionando que es una nueva instancia y con ayuda del método constructor implementamos todos los campos (Para nombre enviamos el texto en minusculas y de igual forma para el correo)
                                // e incluyendo la cantidad de usuarios para hacer que el id_usuario sea unico.
                                user = new Usuario(cantUsuarios, txtNombre.getText(), Integer.parseInt(txtEdad.getText()), txtCorreo.getText(), String.valueOf(passContraseña.getPassword()));
                                user.registrar(user,usuarios); //llamamos el metodo registrar de la clase Usuaruios es donde se almacenará el usuario en un ArrayList
                                
                                //Mostramos un mensaje de que se registro el usuario correctamente.
                                JOptionPane.showMessageDialog(this, "Bienvenido/a " + user.getNombre() + " se ha registrado el usuario correctamente.\nPor favor compruebe iniciando sesión.", "USUARIO AGREGADO EXITOSAMENTE", JOptionPane.INFORMATION_MESSAGE);
                                //Aumentamos la variable para que el siguiente registro sea diferente al anterior y así sucesivamente.
                                cantUsuarios++;
                                
                                //Reestablecemos los valores de todos los campos vaciandolos y dandoles el formato por defecto
                                txtNombre.setText("Ingrese su nombre");
                                txtNombre.setForeground(new java.awt.Color(180,180,180));
                                txtEdad.setText("Ingrese su edad");
                                txtEdad.setForeground(new java.awt.Color(180,180,180));
                                txtCorreo.setText("Ingrese su correo electrónico");
                                txtCorreo.setForeground(new java.awt.Color(180,180,180));
                                passContraseña.setText("************");
                                passContraseña.setForeground(new java.awt.Color(180,180,180));
                            }else{
                                //En caso de no cumplir con la condición de contraseña se muestra un mensaje de error y sereestablece los valores para que el usuario vuelva a digitar la contraseña.
                                JOptionPane.showMessageDialog(this, "Contraseña invalida, por favor crea una contraseña de mínimo 8 cáracteres.\n(Por ejemplo: My_contraseña123)", "CONTRASEÑA CORTA", JOptionPane.HEIGHT);
                                passContraseña.setText("************");
                                passContraseña.setForeground(new java.awt.Color(180,180,180));
                            }
                        }else{
                            //En caso de no cumplir con la condición del correo electrónico se muestra un mensaje de error y sereestablece los valores para que el usuario vuelva a digitar el correo.
                            JOptionPane.showMessageDialog(this, "Correo electrónico invalido o muy corto, por favor digita un correo electrónico válido y de minimo 10 caracteres.\n(Por ejemplo: mycorreo@gmail.com)", "CORREO ELECTRÓNICO INVÁLIDO", JOptionPane.HEIGHT);
                            txtCorreo.setText("Ingrese su correo electrónico");
                            txtCorreo.setForeground(new java.awt.Color(180,180,180));
                        }
                    }else{
                        //En caso de no cumplir con la condición de edad se muestra un mensaje de error y sereestablece los valores para que el usuario vuelva a digitar la edad.
                        JOptionPane.showMessageDialog(this, "La edad debe ser mayor o igual a 18, solo admite personas mayores de edad", "EDAD +18", JOptionPane.HEIGHT);
                        txtEdad.setText("Ingrese su edad");
                        txtEdad.setForeground(new java.awt.Color(180,180,180));
                    }
                }else{
                    //En caso de no cumplir con la condición de nombre se muestra un mensaje de error y sereestablece los valores para que el usuario vuelva a digitar el nombre.
                    JOptionPane.showMessageDialog(this, "El nombre debe tener más de tres carácteres, no puede haber un nombre de uno o dos carácteres.", "NOMBRE DEMASIADO CORTO", JOptionPane.HEIGHT);
                    txtNombre.setText("Ingrese su nombre");
                    txtNombre.setForeground(new java.awt.Color(180,180,180));
                }
            }
            
        }catch(NumberFormatException nfe){ //Captura el error y muestra un mensaje en caso de que ocurra
            JOptionPane.showMessageDialog(this, "El campo de la edad debe ser entero mayor de 18\n Información del error: " + nfe, "EDAD NO VÁLIDA", HEIGHT);
            //Reestablecemos los valores predeterminados que tenia el campo de la edad para que el usuario vuelva a ingresar un entero.
            txtEdad.setText("Ingrese su edad");
            txtEdad.setForeground(new java.awt.Color(180,180,180));
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed
    /*
    * Método que permite ingresar de nuevo a iniciar sesión para entrar al aplicativo
    */
    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        //Declaramos o instanciamos un nuevo objeto de la clase Iniciar sesion
        IniciarSesion login = new IniciarSesion();
        //Mostramos la pantalla de Iniciar sesión.
        login.setVisible(true);
        //En la ventana actual la hacemos invisible para que no se muestre.
        this.setVisible(false);
    }//GEN-LAST:event_btnIniciarSesionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel backgroundDecoracion;
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JToggleButton mostrarPass;
    private javax.swing.JPasswordField passContraseña;
    private javax.swing.JLabel tituloRegistro;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
