/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.safemoney.gui;

import static com.safemoney.gui.IniciarSesion.user;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author JOHANNA
 */
public class frmServicios extends javax.swing.JFrame {

    //Capturamos la ruta donde se encuentra la imagen que queremos colocar como icono del JFrame.
    public final String ruta = "/com/safemoney/imagenes/logo.png";
    

    /**
     * Creates new form frmAhorrosFijos
     */
    public frmServicios() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        lblDineroServicios.setText(String.valueOf(user.servicio.getCantidad()));
        txtDescripcionS.setText(user.servicio.getDescripcion());
        
        //Capturar imagen con ayuda de un toolkit que recupera una imagen 
        Image icono = Toolkit.getDefaultToolkit().getImage(getClass().getResource(ruta));
        //Mostrar imagen en el icono del JFrame
        setIconImage(icono);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        iconLogo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblDineroServicios = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDescripcionS = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        btnAgregarResta = new javax.swing.JButton();
        lblAgregarS = new javax.swing.JLabel();
        btnAgregarSuma = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnRetirarResta = new javax.swing.JButton();
        lblRetirarS = new javax.swing.JLabel();
        btnRetirarSuma = new javax.swing.JButton();
        btnRetirar = new javax.swing.JButton();
        pnlAtras = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 0, 204));

        jPanel1.setBackground(new java.awt.Color(102, 0, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/safemoney/imagenes/alcanciaCerditoPrincipalAlReves.png"))); // NOI18N
        jPanel1.add(iconLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 300, 417, -1));

        jLabel5.setBackground(new java.awt.Color(0, 204, 255));
        jLabel5.setFont(new java.awt.Font("Chewy", 0, 50)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/safemoney/imagenes/bombilloServicios.png"))); // NOI18N
        jLabel5.setText("SERVICIOS");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 60, 390, 180));

        jLabel4.setBackground(new java.awt.Color(0, 204, 255));
        jLabel4.setFont(new java.awt.Font("Chewy", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cantidad");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 150, 30));

        lblDineroServicios.setFont(new java.awt.Font("Chewy", 0, 48)); // NOI18N
        lblDineroServicios.setForeground(new java.awt.Color(255, 255, 255));
        lblDineroServicios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDineroServicios.setText("0");
        jPanel1.add(lblDineroServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 440, 40));

        txtDescripcionS.setFont(new java.awt.Font("Open Sans", 0, 24)); // NOI18N
        jScrollPane3.setViewportView(txtDescripcionS);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 300, 390, 370));

        jLabel2.setBackground(new java.awt.Color(0, 204, 255));
        jLabel2.setFont(new java.awt.Font("Chewy", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Descripción");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 240, 180, 50));

        btnAgregarResta.setFont(new java.awt.Font("Chewy", 0, 24)); // NOI18N
        btnAgregarResta.setText("-");
        btnAgregarResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarRestaActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarResta, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 70, 50));

        lblAgregarS.setFont(new java.awt.Font("Open Sans", 0, 48)); // NOI18N
        lblAgregarS.setForeground(new java.awt.Color(255, 255, 255));
        lblAgregarS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAgregarS.setText("0");
        jPanel1.add(lblAgregarS, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 330, 50));

        btnAgregarSuma.setFont(new java.awt.Font("Chewy", 0, 24)); // NOI18N
        btnAgregarSuma.setText("+");
        btnAgregarSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarSumaActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarSuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 70, 50));

        btnAgregar.setFont(new java.awt.Font("Chewy", 0, 36)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 170, 50));

        btnRetirarResta.setFont(new java.awt.Font("Chewy", 0, 24)); // NOI18N
        btnRetirarResta.setText("-");
        btnRetirarResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarRestaActionPerformed(evt);
            }
        });
        jPanel1.add(btnRetirarResta, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 70, 50));

        lblRetirarS.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        lblRetirarS.setForeground(new java.awt.Color(255, 255, 255));
        lblRetirarS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRetirarS.setText("0");
        jPanel1.add(lblRetirarS, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, 330, 50));

        btnRetirarSuma.setFont(new java.awt.Font("Chewy", 0, 24)); // NOI18N
        btnRetirarSuma.setText("+");
        btnRetirarSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarSumaActionPerformed(evt);
            }
        });
        jPanel1.add(btnRetirarSuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 470, 70, 50));

        btnRetirar.setFont(new java.awt.Font("Chewy", 0, 36)); // NOI18N
        btnRetirar.setText("Retirar");
        btnRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRetirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 550, 170, 50));

        pnlAtras.setBackground(new java.awt.Color(255, 58, 58));
        pnlAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlAtrasMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Chewy", 0, 80)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("<-");

        javax.swing.GroupLayout pnlAtrasLayout = new javax.swing.GroupLayout(pnlAtras);
        pnlAtras.setLayout(pnlAtrasLayout);
        pnlAtrasLayout.setHorizontalGroup(
            pnlAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAtrasLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        pnlAtrasLayout.setVerticalGroup(
            pnlAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAtrasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel1.add(pnlAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1529, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 864, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarRestaActionPerformed
        int cantActual = Integer.parseInt(lblAgregarS.getText());

        if ( cantActual > 0) {
            lblAgregarS.setText(String.valueOf(cantActual - 1000));
        } else {
            JOptionPane.showMessageDialog(this, "No se puede disminuir la cantidad a numeros negativos, recuerda que para agregar dinero debe ser positivo.", "NO SE ACEPTA CANTIDADES NEGATIVAS", HEIGHT);
        }
    }//GEN-LAST:event_btnAgregarRestaActionPerformed

    private void btnAgregarSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarSumaActionPerformed
        int cantActual = Integer.parseInt(lblAgregarS.getText());
        lblAgregarS.setText(String.valueOf(cantActual + 1000));

    }//GEN-LAST:event_btnAgregarSumaActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

        int cantActualAgregar = Integer.parseInt(lblAgregarS.getText());
        double cantActual = Double.parseDouble(lblDineroServicios.getText());

        if (cantActualAgregar > 0) {

            cantActual += cantActualAgregar;
            lblDineroServicios.setText(String.valueOf(cantActual));
            user.servicio.agregarCantidad(cantActualAgregar, cantActual);
            
            lblAgregarS.setText("0");
        }else{
            JOptionPane.showMessageDialog(this, "No se puede agregar 0 a la cantidad, por favor verifique la cantidad a agregar", "NO SE PUEDE AGREGAR 0", HEIGHT);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnRetirarRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarRestaActionPerformed
        int cantActual = Integer.parseInt(lblRetirarS.getText());
        if ( cantActual > 0) {
            lblRetirarS.setText(String.valueOf(cantActual - 1000));
        }else {
            JOptionPane.showMessageDialog(this, "No se puede disminuir la cantidad a numeros negativos, recuerda que para retirar dinero debe ser positivo.", "NO SE ACEPTA CANTIDADES NEGATIVAS", HEIGHT);
        }

    }//GEN-LAST:event_btnRetirarRestaActionPerformed

    private void btnRetirarSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarSumaActionPerformed
        int cantActualRetirar = Integer.parseInt(lblRetirarS.getText());
        double cantActual = Double.parseDouble(lblDineroServicios.getText());
        if(cantActualRetirar < cantActual){
            lblRetirarS.setText(String.valueOf(cantActualRetirar + 1000));
        }else{
            JOptionPane.showMessageDialog(this, "No se puede retirar una cantidad mayor a la que hay disponible en el bolsillo", "DINERO INSUFICIENTE PARA RETIRAR", HEIGHT);
        }
    }//GEN-LAST:event_btnRetirarSumaActionPerformed

    private void btnRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarActionPerformed
        int cantActualRetirar = Integer.parseInt(lblRetirarS.getText());
        double cantActual = Double.parseDouble(lblDineroServicios.getText());

        if (cantActualRetirar >= 0) {
            if(cantActualRetirar <= cantActual){
                cantActual -= cantActualRetirar;
                lblDineroServicios.setText(String.valueOf(cantActual));
                user.servicio.retirarCantidad(cantActualRetirar, cantActual);
                lblRetirarS.setText("0");
            }else{
                JOptionPane.showMessageDialog(this, "No se puede retirar una cantidad mayor a la disponible, por favor verifique la cantidad a retirar", "NO SE PUEDE RETIRAR", HEIGHT);
            }
        }else{
            JOptionPane.showMessageDialog(this, "No se puede retirar 0 a la cantidad, por favor verifique la cantidad a retirar", "NO SE PUEDE RETIRAR 0", HEIGHT);
        }
    }//GEN-LAST:event_btnRetirarActionPerformed

    private void pnlAtrasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAtrasMousePressed
        FrmPrincipal principal = new FrmPrincipal();
        principal.setVisible(true);
        this.setVisible(false); //Modificamos la visibilidad de este JFrame para no estar abriendo tantas ventanas.

        user.servicio.setDescripcion(txtDescripcionS.getText());
        user.servicio.cantidadTotal = 0;
        user.servicio.cantidadTotal = Double.parseDouble(lblDineroServicios.getText());
    }//GEN-LAST:event_pnlAtrasMousePressed

  
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAgregarResta;
    private javax.swing.JButton btnAgregarSuma;
    private javax.swing.JButton btnRetirar;
    private javax.swing.JButton btnRetirarResta;
    private javax.swing.JButton btnRetirarSuma;
    private javax.swing.JLabel iconLogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAgregarS;
    private javax.swing.JLabel lblDineroServicios;
    private javax.swing.JLabel lblRetirarS;
    private javax.swing.JPanel pnlAtras;
    private javax.swing.JTextPane txtDescripcionS;
    // End of variables declaration//GEN-END:variables
}
