
package com.safemoney.gui;

import com.safemoney.clases.Usuario;
import static com.safemoney.gui.IniciarSesion.user;
import static com.safemoney.gui.IniciarSesion.usuarios;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

public class frmUsuario extends javax.swing.JFrame {

    /**
     * Creates new form frmUsuario
     */
    
    //Capturamos la ruta donde se encuentra la imagen que queremos colocar como icono del JFrame.
    public final String ruta = "/com/safemoney/imagenes/logo.png";
    //Id es el identificador unico de los usuarios para poder acceder a toda su información con un solo dato.
    private int id = user.getIdUsuario();
    //Almacenamos en una variable el nombre del usuario actual que haya iniciado sesión.
    private String nombre = user.getNombre();
    //Almacenamos en una variable el correo del usuario actual que haya iniciado sesión.
    private String correo = user.getCorreo();
    //Almacenamos en una variable la contraseña del usuario actual que haya iniciado sesión.
    private String contraseña = user.getContraseña();
    //Almacenamos en una variable la edad del usuario actual que haya iniciado sesión.
    private int edad = user.getEdad();
    //Todos estos datos se utilizaran más adelante para mostrarlos en algunos campos.
    
    public frmUsuario() {
        this.setLocationRelativeTo(null);
        
        initComponents();
        txtNombre.setText(nombre); //Al iniciar el formulario el campo de nombre, lo modificamos a la variable nombre.
        txtEdad.setText(String.valueOf(edad)); //Al iniciar el formulario el campo de edad, parseamos la edad para que se muestre como String y mostramos la edad.
        txtCorreo.setText(correo); //Al iniciar el formulario el campo de correo, lo modificamos a la variable correo.
        passContraseña.setText(contraseña); //Al iniciar el formulario el campo de contraseña, lo modificamos a la variable contraseña.
        
        //Capturar imagen con ayuda de un toolkit que recupera una imagen 
        Image icono = Toolkit.getDefaultToolkit().getImage(getClass().getResource(ruta));
        //Mostrar imagen en el icono del JFrame
        setIconImage(icono);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TituloUsuario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        mostrarPass = new javax.swing.JToggleButton();
        passContraseña = new javax.swing.JPasswordField();
        btnCerrarSesión = new javax.swing.JButton();
        btnModificarDatos = new javax.swing.JButton();
        btnEliminarUsuario = new javax.swing.JButton();
        pnlAtras = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setSize(new java.awt.Dimension(1536, 864));

        jPanel1.setBackground(new java.awt.Color(132, 97, 244));
        jPanel1.setForeground(new java.awt.Color(132, 97, 244));
        jPanel1.setLayout(null);

        TituloUsuario.setFont(new java.awt.Font("Chewy", 0, 90)); // NOI18N
        TituloUsuario.setForeground(new java.awt.Color(255, 255, 255));
        TituloUsuario.setText("USUARIO");
        jPanel1.add(TituloUsuario);
        TituloUsuario.setBounds(520, 70, 330, 90);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/safemoney/imagenes/imagenUser.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(1000, 120, 500, 500);

        jLabel3.setFont(new java.awt.Font("Chewy", 0, 44)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Contraseña:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(80, 510, 210, 40);

        jLabel4.setFont(new java.awt.Font("Chewy", 0, 44)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Nombre:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(130, 240, 160, 40);

        jLabel5.setFont(new java.awt.Font("Chewy", 0, 44)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Edad:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(130, 330, 160, 40);

        jLabel6.setFont(new java.awt.Font("Chewy", 0, 44)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Correo:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(130, 420, 160, 40);

        txtNombre.setEditable(false);
        txtNombre.setBackground(new java.awt.Color(240, 236, 255));
        txtNombre.setFont(new java.awt.Font("Open Sans", 0, 19)); // NOI18N
        txtNombre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(132, 97, 244), 1, true));
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreKeyPressed(evt);
            }
        });
        jPanel1.add(txtNombre);
        txtNombre.setBounds(400, 240, 490, 40);

        txtEdad.setEditable(false);
        txtEdad.setBackground(new java.awt.Color(240, 236, 255));
        txtEdad.setFont(new java.awt.Font("Open Sans", 0, 19)); // NOI18N
        txtEdad.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(132, 97, 244), 1, true));
        txtEdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEdadKeyPressed(evt);
            }
        });
        jPanel1.add(txtEdad);
        txtEdad.setBounds(400, 330, 490, 40);

        txtCorreo.setEditable(false);
        txtCorreo.setBackground(new java.awt.Color(240, 236, 255));
        txtCorreo.setFont(new java.awt.Font("Open Sans", 0, 19)); // NOI18N
        txtCorreo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(132, 97, 244), 1, true));
        txtCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCorreoKeyPressed(evt);
            }
        });
        jPanel1.add(txtCorreo);
        txtCorreo.setBounds(400, 420, 490, 40);

        mostrarPass.setBackground(new java.awt.Color(158, 217, 255));
        mostrarPass.setForeground(new java.awt.Color(255, 255, 255));
        mostrarPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/safemoney/imagenes/ojoCerrado.png"))); // NOI18N
        mostrarPass.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(132, 97, 244), 1, true));
        mostrarPass.setContentAreaFilled(false);
        mostrarPass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mostrarPass.setFocusPainted(false);
        mostrarPass.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                mostrarPassItemStateChanged(evt);
            }
        });
        mostrarPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarPassActionPerformed(evt);
            }
        });
        jPanel1.add(mostrarPass);
        mostrarPass.setBounds(850, 510, 40, 40);

        passContraseña.setEditable(false);
        passContraseña.setBackground(new java.awt.Color(240, 236, 255));
        passContraseña.setFont(new java.awt.Font("Open Sans", 0, 19)); // NOI18N
        passContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passContraseñaKeyPressed(evt);
            }
        });
        jPanel1.add(passContraseña);
        passContraseña.setBounds(400, 510, 490, 40);

        btnCerrarSesión.setBackground(new java.awt.Color(240, 236, 255));
        btnCerrarSesión.setFont(new java.awt.Font("Chewy", 0, 29)); // NOI18N
        btnCerrarSesión.setForeground(new java.awt.Color(132, 97, 244));
        btnCerrarSesión.setText("Cerrar Sesión");
        btnCerrarSesión.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(132, 97, 244), 1, true));
        btnCerrarSesión.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesiónActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrarSesión);
        btnCerrarSesión.setBounds(1260, 670, 230, 80);

        btnModificarDatos.setBackground(new java.awt.Color(240, 236, 255));
        btnModificarDatos.setFont(new java.awt.Font("Chewy", 0, 29)); // NOI18N
        btnModificarDatos.setForeground(new java.awt.Color(132, 97, 244));
        btnModificarDatos.setText("Modificar Datos");
        btnModificarDatos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(132, 97, 244), 1, true));
        btnModificarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarDatosActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificarDatos);
        btnModificarDatos.setBounds(50, 670, 230, 80);

        btnEliminarUsuario.setBackground(new java.awt.Color(240, 236, 255));
        btnEliminarUsuario.setFont(new java.awt.Font("Chewy", 0, 29)); // NOI18N
        btnEliminarUsuario.setForeground(new java.awt.Color(132, 97, 244));
        btnEliminarUsuario.setText("Eliminar Usuario");
        btnEliminarUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(132, 97, 244), 1, true));
        btnEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminarUsuario);
        btnEliminarUsuario.setBounds(620, 670, 230, 80);

        pnlAtras.setBackground(new java.awt.Color(255, 58, 58));
        pnlAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlAtrasMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Chewy", 0, 80)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("<-");

        javax.swing.GroupLayout pnlAtrasLayout = new javax.swing.GroupLayout(pnlAtras);
        pnlAtras.setLayout(pnlAtrasLayout);
        pnlAtrasLayout.setHorizontalGroup(
            pnlAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAtrasLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        pnlAtrasLayout.setVerticalGroup(
            pnlAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAtrasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel1.add(pnlAtras);
        pnlAtras.setBounds(40, 20, 120, 80);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1536, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 864, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /*
    * Método que se ejecuta al presionar el boton de mostrar password (icono de ojo cerrado)
    */
    private void mostrarPassItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_mostrarPassItemStateChanged
        if(mostrarPass.isSelected()){ //Verifica si el botón de mostrarPass esta seleccionado
            mostrarPass.setBackground(new java.awt.Color(158,217,255)); //Modifica el color de fondo del botón.
        }
        else{
            mostrarPass.setBackground(new java.awt.Color(242,250,255)); //Modifica el color de fondo del botón.
        }
    }//GEN-LAST:event_mostrarPassItemStateChanged
    /*
    * Método que se ejecuta al presionar el boton de mostrar password (icono de ojo cerrado)
    */
    private void mostrarPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarPassActionPerformed
        if(mostrarPass.isSelected()){ //Verifica si el botón mostrar parrword está seleccionado
            mostrarPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/safemoney/imagenes/ojoAbierto.png"))); //Modifica el icono a una nueva imagen tipo icono de una ruta o url dentro del proyecto (ojo abierto).
            passContraseña.setEchoChar((char)0); //Al llamar el metodo setEchoChar((char)0) permite mostrar la contraseña reemplazando todos los caracteres a caracteres visibles dentro del campo.
        }else{
            mostrarPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/safemoney/imagenes/ojoCerrado.png"))); //Modifica el icono a una nueva imagen de tipo icono de una ruta existente de una ruta o url dentro del proyecto (ojo cerrado) (icono por defecto).
            passContraseña.setEchoChar('*'); //Al modificar los caracteres por * cada uno se oculta con ese caracter.
        }
    }//GEN-LAST:event_mostrarPassActionPerformed
    /*
    * Método que se ejecuta al presionar una tecla en el campo de nombre
    */
    private void txtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyPressed

        
        if(txtNombre.isEditable() && evt.getKeyCode() == KeyEvent.VK_ENTER){ //Valida que el campo de nombre sea editable y al mismo tiempo que al obtener la tecla presionada sea igual a la tecla enter <-
            if(!txtNombre.getText().isEmpty()){ //Valida que el campo de nombre no sea vacio
                if(txtNombre.getText().length() >= 3){
                    nombre = txtNombre.getText(); //A la variable global nombre se le asigna un nuevo valor que es el texto del campo nombre que se modifique
                    user.setNombre(nombre); //Al nombre de user (el usuario que se inició sesión) se le modifica el nombre.
                    usuarios.set(id, user); //Modificamos todo el usuario del id actual (La sesión actual) y se cambia con el usuario que acabamos de instanciar al ArrayList de usuarios.
                    txtNombre.setEditable(false); //Modificamos la edición para que no se pueda editar
                    //Por ultimo mostramos un mensaje de que se actualizo el nombre con éxito.
                    JOptionPane.showMessageDialog(this, "Se actualizó el nombre " + nombre + " con éxito", "ACTUALIZACIÓN CORRECTA", JOptionPane.INFORMATION_MESSAGE);
                }else{
                    //En caso de no cumplir con la condición de nombre se muestra un mensaje de error y sereestablece los valores para que el usuario vuelva a digitar el nombre.
                    JOptionPane.showMessageDialog(this, "El nombre debe tener más de tres carácteres, no puede haber un nombre de uno o dos carácteres.", "NOMBRE DEMASIADO CORTO", JOptionPane.HEIGHT);
                    txtNombre.setText(nombre);
                }  
            }else{ //En caso de que el campo este vacio que muestre un mensaje de que el campo se encuentra vacio.
                JOptionPane.showMessageDialog(this, "El campo de nombre no puede estar vacio, por favor coloca un nombre", "CAMPO VACIO", HEIGHT);
            }
        }
    }//GEN-LAST:event_txtNombreKeyPressed
    /*
    * Método que se ejecuta luego de darle click al boton modificar.
    */
    private void btnModificarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarDatosActionPerformed
        //Arreglo de opciones disponibles para actualizar los distintos datos para mostrar estas opciones dentro del JOptionPane (alerta o ventana emergente)
        String[] datos = {"Nombre", "Edad", "Correo", "Contraseña"};
        // Leemos una opcion a traves de un showOptionDialog y mostramos las opciones del arreglo previamente mencionado
        int opcion = JOptionPane.showOptionDialog(this, "Selecciona el dato que quieres modificar", "MODIFICAR DATO", JOptionPane.INFORMATION_MESSAGE, JOptionPane.PLAIN_MESSAGE, null , datos, datos[0]);
        
        //Mostramos al usuario como debe actualizar los datos, para tener claridad de como se hace.
        JOptionPane.showMessageDialog(this, "Para almacenar los datos:\n\t1. cambia el valor en el campo \n\t2. presiona la tecla enter <-", "INFORMACIÓN DE ACTUALIZACIÓN DE DATOS", JOptionPane.INFORMATION_MESSAGE);
        //Dependiendo de la lectura de la opcion habilita la edicion del campo para que se pueda modificar.
        switch(opcion){
            case 0 -> {
                txtNombre.setEditable(true);
            }
            case 1 ->{
                txtEdad.setEditable(true);
            }
            case 2 ->{
                txtCorreo.setEditable(true);
            }
            case 3 ->{
                passContraseña.setEditable(true);
            }
        }
    }//GEN-LAST:event_btnModificarDatosActionPerformed
    /*
    * Al darle click a un "botón" simulado con un JPanel al presionar con el mouse se ejecuta este método
    */
    private void pnlAtrasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAtrasMousePressed
        FrmPrincipal principal = new FrmPrincipal();
        principal.setVisible(true);//Modificamos la visibilidad del JFrame.
        this.setVisible(false); //Modificamos la visibilidad de este JFrame para no estar abriendo tantas ventanas.
    }//GEN-LAST:event_pnlAtrasMousePressed
    /*
    * Método que se ejecuta al darle click al botón Cerrar Sesión
    */
    private void btnCerrarSesiónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesiónActionPerformed
        IniciarSesion login = new IniciarSesion();
        login.setVisible(true); //Hacemos visible el JFrame
        IniciarSesion.user = null; //El usuario que ingresamos al iniciar sesion lo volvemos nulo para que se reestablezcan los valores y poder volver a Iniciar sesion
        this.setVisible(false); //Esta ventana no la hacemos visible
    }//GEN-LAST:event_btnCerrarSesiónActionPerformed
    /*
    * Método que se ejecuta al presionar alguna tecla dentro del campo edad.
    */
    private void txtEdadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEdadKeyPressed
        
        
        //Validamos que el campo edad sea editable y al mismo tiempo que la tecla que se presionó es igual a la tecla enter <-
        if( txtEdad.isEditable() && evt.getKeyCode() == KeyEvent.VK_ENTER){
            //Intenta ejecutar todo este bloque de codigo y en caso de generar una excepcion de NumberFormatException ejecuta algo en especial.
            try{
                //Validamos si el campo edad está vacio.
                if(txtEdad.getText().isEmpty()){
                    //Mostramos un mensaje de que el campo edad no puede estar vacio.
                    JOptionPane.showMessageDialog(this, "El campo de Edad no puede estar vacio, coloca una edad mayoro igual a 18", "CAMPO VACIO", HEIGHT);
                }
                else{ //En caso de que el campo de edad no este vacio 
                    if(Integer.parseInt(txtEdad.getText())>=18){ //Hacemos el parseo de lo que haya en el campo de edad a entero y validamos que ese número sea mayor o igual a 18 
                        //Actualizamos la variable edad, parseando el texto de edad a entero para poderlo actuializar.
                        edad = Integer.parseInt(txtEdad.getText());
                        //De user seteamos o modificamos la edad por edad.
                        user.setEdad(edad);
                        //Del ArrayList Usuarios actualizamos el usuario con el id actual por la instancia que creamos anteriormente.
                        usuarios.set(id, user);
                        //Modificamos que el campo no se pueda editar.
                        txtEdad.setEditable(false);
                        
                        //Por ultimo, mostramos un mensaje de que se actualizó la edad con éxito.
                        JOptionPane.showMessageDialog(this, "Se actualizó la edad " + edad + " con éxito", "ACTUALIZACIÓN CORRECTA", JOptionPane.INFORMATION_MESSAGE);
                        
                    }else{ //En caso de que no se cumpla la condicion de la edad es mayor o igual a 18
                        //Mostramos un mensaje donde especifique que la edad debe ser mayor o igual a 18
                        JOptionPane.showMessageDialog(this, "La edad debe ser mayor o igual a 18, solo admite personas mayores de edad", "EDAD +18", JOptionPane.HEIGHT);
                        //Modificamos el campo para que se muestre como estaba antes de actualizar.
                        txtEdad.setText(String.valueOf(edad));
                        //Volvemos el campo ineditable.
                        txtEdad.setEditable(false);
                    }
                }
            }catch(NumberFormatException nf){ //Captura las excepciones que se den en cuanto a que el usuario ingrese un dato que no sea númerico.
                //Mostramos la información del error
                JOptionPane.showMessageDialog(this, "El campo de la edad debe ser entero mayor de 18\nInformación del error: " + nf, "EDAD NO VÁLIDA", HEIGHT);
                //Modificamos el texto del campo edad a la edad que se tenia antes de darle click al botón modificar
                txtEdad.setText(String.valueOf(edad));
                //Hacemos que el campo no se pueda editar
                txtEdad.setEditable(false);
            }
        }
    }//GEN-LAST:event_txtEdadKeyPressed
    /*
    * Método que se ejecuta cuando en el campo del correo se presiona alguna tecla
    */
    private void txtCorreoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoKeyPressed
        //Validamos si el campo del correo es editable y al mismo tiempo si la tecla presionada es igual a la tecla enter.
        if(txtCorreo.isEditable() && evt.getKeyCode() == KeyEvent.VK_ENTER){
            //Validamos si el campo del correo electrónico está vacio
            if(txtCorreo.getText().isEmpty()){
                //Mostramos un mensaje donde muestre que el campo del el correo no puede estar vacio.
                JOptionPane.showMessageDialog(this, "El campo de Correo no puede estar vacio, coloca un correo electronico válido", "CAMPO VACIO", HEIGHT);                
            }else{
                if(txtCorreo.getText().contains("@") && txtCorreo.getText().length() >= 10){ //Validamos que en todo lo que el usuario ingrese exista un @ para hacer válido el correo y al mismo tiempo que sea mayor o igual a 10 cáracteres
                    
                    correo = txtCorreo.getText(); //Modificamos la variable de correo con el correo agregado dentro del campo
                    user.setCorreo(correo); //Modificamos el correo del user (usuario que ya habia iniciado Sesión).
                    usuarios.set(id, user); //En el ArrayList modificamos el usuario con la instancia que previamente habiamos creado.
                    txtCorreo.setEditable(false); //Modificamos la edición del campo correo, para que no se pueda editar
                    //Por último, mostramos un mensaje que diga que el correo se actualizó con éxito.
                    JOptionPane.showMessageDialog(this, "Se actualizó el correo " + correo + " con éxito", "ACTUALIZACIÓN CORRECTA", JOptionPane.INFORMATION_MESSAGE);
                }
                else{ //Si no se cumple la condición 
                    //Mostrar un mensaje donde indique que el correo es invalido o es demasiado corto para ser un correo.
                    JOptionPane.showMessageDialog(this, "El correo es inválido o demasiado corto para ser un correo, por favor coloca un correo válido y de mínimo 10 cáracteres.\n(Por ejemplo: mycorreo@gmail.com)", ruta, HEIGHT);
                    //Modificamos el campo del correo al correo que teniamos antes de modificar.
                    txtCorreo.setText(correo);
                    //Hacemos que el campo de correo sea ineditable.
                    txtCorreo.setEditable(false);
                }
            }
        }
    }//GEN-LAST:event_txtCorreoKeyPressed
    /*
    * Método que se ejecuta cuando se presiona alguna tecla dentro del campo de contraseña
    */
    private void passContraseñaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passContraseñaKeyPressed
        //Validamos que el campo contraseña sea editable y al mismo tiempo que la tecla que se haya presionado sea igual a la tecla enter <-
        if(passContraseña.isEditable() && evt.getKeyCode() == KeyEvent.VK_ENTER){
            //Parseamos la contraseña para validar si el campo de contraseña esta vacio.
            if(String.valueOf(passContraseña.getPassword()).isEmpty()){
                //Mostramos un mensaje donde diga que el campo de contraseña no puede estar vacio.
                JOptionPane.showMessageDialog(this, "El campo de Contraseña no puede estar vacio, coloca una contraseña", "CAMPO VACIO", HEIGHT);
            }
            else{ //Si no se cumple esta condición
                //Parseamos el valor de la contraseña y validamos que la cantidad de cáracteres supere el valor de 8.
                if(String.valueOf(passContraseña.getPassword()).length() >= 8){ //Valida que la contraseña sea mayor o igual a 8 caracteres para tener una contraseña segura.
                    contraseña = String.valueOf(passContraseña.getPassword()); //A la variable global contraseña, le asignamos un nuevo valor del parseo de la contraseña a cadena de texto.
                    user.setContraseña(contraseña); //Modificamos la contraseña del usuario que esta actualmente en sesión.
                    IniciarSesion.usuarios.set(id, user); //Del ArrayList (donde estamos almacenando los usuarios) modificar segun el id del usuario (de la sesion actual) a la instancia que recientemente creamos.
                    passContraseña.setEditable(false); //Modificamos la edición del campo de la contraseña, para que no se pueda editar
                    //Mostramos un mensaje qye se actualizó la contrasseña con éxito.
                    JOptionPane.showMessageDialog(this, "Se actualizó la contraseña " + contraseña + " con éxito", "ACTUALIZACIÓN CORRECTA", JOptionPane.INFORMATION_MESSAGE);
                }else{
                    //En caso de no cumplir con la condición de contraseña se muestra un mensaje de error
                    JOptionPane.showMessageDialog(this, "Contraseña invalida, por favor crea una contraseña de mínimo 8 cáracteres.\n(Por ejemplo: My_contraseña123)", "CONTRASEÑA CORTA", JOptionPane.HEIGHT);
                    //Modificamos el texto del campo de contraseña y le dejamos la contraseña que tenia antes de editar.
                    passContraseña.setText(contraseña);
                    //Modificamos la edicion del campo contraseña para que no se pueda editar el campo
                    passContraseña.setEditable(false);
                }
            }
        }
    }//GEN-LAST:event_passContraseñaKeyPressed
    /*
    * Método que se ejecuta al presionar el boton de eliminar usuario.
    */
    private void btnEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarUsuarioActionPerformed
        
        usuarios.remove(id); //De la lista (ArrayList) de usuarios eliminamos el usuario actual de la sesion donde está
        IniciarSesion login = new IniciarSesion(); //Hacemos visible esta instancia para que se muestre.
        login.setVisible(true);
        IniciarSesion.user = null; //Hacemos nulo el usuario para reestablecer la sesión actual (lo mismo hace cerrar sesión)
        this.setVisible(false); //El JFrame donde estamos lo ocultamos.
        
    }//GEN-LAST:event_btnEliminarUsuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TituloUsuario;
    private javax.swing.JButton btnCerrarSesión;
    private javax.swing.JButton btnEliminarUsuario;
    private javax.swing.JButton btnModificarDatos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton mostrarPass;
    private javax.swing.JPasswordField passContraseña;
    private javax.swing.JPanel pnlAtras;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
