/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.safemoney.gui;


import com.formdev.flatlaf.intellijthemes.FlatArcIJTheme;
import com.safemoney.clases.Usuario;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;


/**
 *
 * @author wilsa
 */
public class IniciarSesion extends javax.swing.JFrame {

    //Capturamos la ruta donde se encuentra la imagen que queremos colocar como icono del JFrame
    public final String ruta = "/com/safemoney/imagenes/logo.png";
    //ArrayList en el cual se almacenarán los diferentes usuarios de tipo Usuario
    public static ArrayList<Usuario> usuarios = new ArrayList<>();
    // Usuario para obtener que usuario se loguea.
    public static Usuario user;
    // Numero de usuario logueado.
    public static int usuarioLog; 
    
    /**
     * Creates new form IniciarSesion
     */
    
    public IniciarSesion() {
        this.setLocationRelativeTo(null);
        initComponents();
        
        
        //Capturar imagen con ayuda de un toolkit que recupera una imagen 
        Image icono = Toolkit.getDefaultToolkit().getImage(getClass().getResource(ruta));
        //Mostrar imagen en el icono del JFrame
        setIconImage(icono);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoPrincipal = new javax.swing.JPanel();
        FondoDecoracion = new javax.swing.JPanel();
        Frase1 = new javax.swing.JLabel();
        Frase1_1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TituloIniciarSesion1 = new javax.swing.JLabel();
        TituloIniciarSesion2 = new javax.swing.JLabel();
        mostrarPass = new javax.swing.JToggleButton();
        passContraseña = new javax.swing.JPasswordField();
        TituloIniciarSesion = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        btnIniciarSesion = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Safe Money $$$");
        setLocation(new java.awt.Point(0, 0));
        setSize(new java.awt.Dimension(1536, 864));

        FondoPrincipal.setBackground(new java.awt.Color(189, 231, 255));
        FondoPrincipal.setAlignmentX(0.0F);
        FondoPrincipal.setAlignmentY(0.0F);
        FondoPrincipal.setLayout(null);

        FondoDecoracion.setBackground(new java.awt.Color(56, 182, 255));
        FondoDecoracion.setLayout(null);

        Frase1.setFont(new java.awt.Font("Railey-PersonalUse", 0, 60)); // NOI18N
        Frase1.setForeground(new java.awt.Color(255, 255, 255));
        Frase1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Frase1.setText("con nosotros");
        FondoDecoracion.add(Frase1);
        Frase1.setBounds(150, 760, 420, 80);

        Frase1_1.setFont(new java.awt.Font("Railey-PersonalUse", 0, 60)); // NOI18N
        Frase1_1.setForeground(new java.awt.Color(255, 255, 255));
        Frase1_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Frase1_1.setText("Gestiona tus ingresos");
        FondoDecoracion.add(Frase1_1);
        Frase1_1.setBounds(150, 680, 420, 80);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/safemoney/imagenes/imagenIniciarSesion.png"))); // NOI18N
        FondoDecoracion.add(jLabel2);
        jLabel2.setBounds(0, 30, 630, 610);

        FondoPrincipal.add(FondoDecoracion);
        FondoDecoracion.setBounds(896, -26, 670, 930);

        TituloIniciarSesion1.setFont(new java.awt.Font("Chewy", 0, 46)); // NOI18N
        TituloIniciarSesion1.setForeground(new java.awt.Color(56, 182, 255));
        TituloIniciarSesion1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloIniciarSesion1.setText("Usuario:");
        FondoPrincipal.add(TituloIniciarSesion1);
        TituloIniciarSesion1.setBounds(20, 300, 280, 80);

        TituloIniciarSesion2.setFont(new java.awt.Font("Chewy", 0, 46)); // NOI18N
        TituloIniciarSesion2.setForeground(new java.awt.Color(56, 182, 255));
        TituloIniciarSesion2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloIniciarSesion2.setText("Contraseña:");
        FondoPrincipal.add(TituloIniciarSesion2);
        TituloIniciarSesion2.setBounds(20, 430, 280, 80);

        mostrarPass.setBackground(new java.awt.Color(158, 217, 255));
        mostrarPass.setForeground(new java.awt.Color(255, 255, 255));
        mostrarPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/safemoney/imagenes/ojoCerrado.png"))); // NOI18N
        mostrarPass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(189, 231, 255)));
        mostrarPass.setContentAreaFilled(false);
        mostrarPass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mostrarPass.setFocusPainted(false);
        mostrarPass.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                mostrarPassItemStateChanged(evt);
            }
        });
        mostrarPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarPassActionPerformed(evt);
            }
        });
        FondoPrincipal.add(mostrarPass);
        mostrarPass.setBounds(790, 450, 40, 40);

        passContraseña.setBackground(new java.awt.Color(242, 250, 255));
        passContraseña.setFont(new java.awt.Font("Open Sans", 0, 19)); // NOI18N
        passContraseña.setForeground(new java.awt.Color(180, 180, 180));
        passContraseña.setText("************");
        passContraseña.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(189, 231, 255), 1, true));
        passContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passContraseñaMousePressed(evt);
            }
        });
        FondoPrincipal.add(passContraseña);
        passContraseña.setBounds(320, 450, 510, 40);

        TituloIniciarSesion.setFont(new java.awt.Font("Chewy", 0, 73)); // NOI18N
        TituloIniciarSesion.setForeground(new java.awt.Color(56, 182, 255));
        TituloIniciarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloIniciarSesion.setText("Iniciar Sesión");
        FondoPrincipal.add(TituloIniciarSesion);
        TituloIniciarSesion.setBounds(170, 60, 480, 80);

        txtUsuario.setBackground(new java.awt.Color(242, 250, 255));
        txtUsuario.setFont(new java.awt.Font("Open Sans", 0, 19)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(180, 180, 180));
        txtUsuario.setText("Ingresar nombre o correo");
        txtUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(189, 231, 255), 1, true));
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtUsuarioMousePressed(evt);
            }
        });
        FondoPrincipal.add(txtUsuario);
        txtUsuario.setBounds(320, 320, 510, 40);

        btnIniciarSesion.setBackground(new java.awt.Color(56, 182, 255));
        btnIniciarSesion.setFont(new java.awt.Font("Chewy", 0, 29)); // NOI18N
        btnIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarSesion.setText("Iniciar Sesión");
        btnIniciarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });
        FondoPrincipal.add(btnIniciarSesion);
        btnIniciarSesion.setBounds(520, 640, 200, 90);

        btnRegistrar.setBackground(new java.awt.Color(56, 182, 255));
        btnRegistrar.setFont(new java.awt.Font("Chewy", 0, 29)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registrar");
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        FondoPrincipal.add(btnRegistrar);
        btnRegistrar.setBounds(170, 640, 200, 90);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(FondoPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 1536, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(FondoPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 864, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /*
    * Método que permite entrar a la ventana de FrmRegistro, cuando se presione el botón registrar
    */
    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        FrmRegistro registro = new FrmRegistro(); //Crea una nueva ventana como si de una instancia se tratase para ingresar a una nueva ventana incluyendo los objetos que se tengan allí.
        registro.setVisible(true); //Llamamos al método que permite modificar la visibilidad de la ventana, en este caso la volvemos verdadera
        this.setVisible(false); //Llamamos al método que permite modificar la visibilidad de la ventana actual, en ese caso la volvemos falsa.
    }//GEN-LAST:event_btnRegistrarActionPerformed
    /*
    * Método que ocurre cuando hacemos click al botón Iniciar Sesión
    */
    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        //Creamos un nuevo usuario para validar la información con el usuario que se recupere de un método Iniciar Sesión.
        
        Usuario validar = new Usuario();
        //Primero validamos que ambos de los campos está con el mensaje por defecto.
        if(txtUsuario.getText().equals("Ingresar nombre o correo") || String.valueOf(passContraseña.getPassword()).equals("************")){
            //Mostramos un mensaje que los campos esán vacios.
            JOptionPane.showMessageDialog(this, "Los campos de Usuario y Contraseña están vacios", "CAMPOS VACIOS", HEIGHT);
        }
        else{ //En caso de que no sean igual al texto por defecto.
            //En el método inicarSesion busca el usuario que tenga estas igualdades y lo retorna, luego lo  almacenamos en una variable del mismo tipo Usuario.
            user = validar.iniciarSesion(txtUsuario.getText(), txtUsuario.getText(), String.valueOf(passContraseña.getPassword()), usuarios);
            //Validamos que el valor retornado no sea nulo
            if(user != null){
                //Crea una instancia de Inicio de la clase FrmPrincipal.
                FrmPrincipal inicio = new FrmPrincipal();
                //Lo hacemos visible.
                inicio.setVisible(true);
                //La ventana actual se volverá no visible.
                this.setVisible(false);
                
            }else{ //En aso de ser nulos mostrar un mensaje de Usuario o contraseña erroneas.
                //Mostramos un mensaje de que el usuario o contraseña no existen o son inválidos
                JOptionPane.showMessageDialog(this, "Usuario o contraseña invalidos o incorrectos.\nPor favor, verifica los campos y vuelve a intentar.", "USUARIO O CONTRASEÑA INVÁLIDOS", HEIGHT);
                
                //Reestablecemos el color y el texto de los campos de Usuario: y Contraseña:
                txtUsuario.setText("Ingresar nombre o correo"); //Modifica el texto a un texto por defecto
                txtUsuario.setForeground(new java.awt.Color(180,180,180)); //Modifica el color al color por defecto el cual es gris claro.
                passContraseña.setText("************"); //Modifica el texto a un texto por defecto
                passContraseña.setForeground(new java.awt.Color(180,180,180)); //Modifica el color al color por defecto el cual es gris claro.
            }
        }
    }//GEN-LAST:event_btnIniciarSesionActionPerformed
    /*
    * Método que se ejecuta al hacer click en el campo de usuario.
    */
    private void txtUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMousePressed
        
        if(txtUsuario.getText().equals("Ingresar nombre o correo")){ //Valida si el texto del campo usuario es igual al texto por defecto.
            txtUsuario.setText(""); //Modifica el texto a vacio
            txtUsuario.setForeground(Color.BLACK); //Modifica el color del texto a negro.
        }
        if(String.valueOf(passContraseña.getPassword()).isEmpty()){ //Realiza el parseo a cadena de texto, y valida si el campo está vacio.
            passContraseña.setText("************"); //Modifica el texto al texto por defecto.
            passContraseña.setForeground(new java.awt.Color(180,180,180)); //Modifica el color del texto a gris claro (Color por defecto).
        }
    }//GEN-LAST:event_txtUsuarioMousePressed
    /*
    * Método que se ejecuta al hacer click en el campo de contraseña.
    */
    private void passContraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passContraseñaMousePressed
        
        if(String.valueOf(passContraseña.getPassword()).equals("************")){ //Realiza el parceo de un char[] a una cadena de texto y valida si el campo de contraseña es igual al texto por defecto.
            passContraseña.setText(""); //Modifica  el texto a vacio para digitar algo nuevo.
            passContraseña.setForeground(Color.BLACK); //Modifica el color del texto a negro
        }
        if(txtUsuario.getText().isEmpty()){ //Valida si el campo de usuario esta vacio
            txtUsuario.setText("Ingresar nombre o correo"); //Modifica el texto al texto por defecto
            txtUsuario.setForeground(new java.awt.Color(180,180,180)); //Modifica el color del texto a gris claro (Color por defecto).
        }
    }//GEN-LAST:event_passContraseñaMousePressed
    /*
    * Método que se ejecuta al presionar el boton de mostrar password (icono de ojo cerrado)
    */
    private void mostrarPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarPassActionPerformed
        if(mostrarPass.isSelected()){ //Verifica si el botón mostrar parrword está seleccionado
            mostrarPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/safemoney/imagenes/ojoAbierto.png"))); //Modifica el icono a una nueva imagen tipo icono de una ruta o url dentro del proyecto (ojo abierto).
            passContraseña.setEchoChar((char)0); //Al llamar el metodo setEchoChar((char)0) permite mostrar la contraseña reemplazando todos los caracteres a caracteres visibles dentro del campo.
        }else{
            mostrarPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/safemoney/imagenes/ojoCerrado.png"))); //Modifica el icono a una nueva imagen de tipo icono de una ruta existente de una ruta o url dentro del proyecto (ojo cerrado) (icono por defecto).
            passContraseña.setEchoChar('*'); //Al modificar los caracteres por * cada uno se oculta con ese caracter.
        }
    }//GEN-LAST:event_mostrarPassActionPerformed
    /*
    * Método que se ejecuta para comprobar si el boton esta seleccionado o no
    */
    private void mostrarPassItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_mostrarPassItemStateChanged
        if(mostrarPass.isSelected()){ //Verifica si el botón de mostrarPass esta seleccionado
            mostrarPass.setBackground(new java.awt.Color(158,217,255)); //Modifica el color de fondo del botón.
        } 
        else{
            mostrarPass.setBackground(new java.awt.Color(242,250,255)); //Modifica el color de fondo del botón.
        }
    }//GEN-LAST:event_mostrarPassItemStateChanged

    /**
     * @param args the command line arguments
     * @throws javax.swing.UnsupportedLookAndFeelException
     */
    //main
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        UIManager.setLookAndFeel(new FlatArcIJTheme());
        UIManager.put("Button.arc", 42);
        UIManager.put("Panel.arc", 51);
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IniciarSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FondoDecoracion;
    private javax.swing.JPanel FondoPrincipal;
    private javax.swing.JLabel Frase1;
    private javax.swing.JLabel Frase1_1;
    private javax.swing.JLabel TituloIniciarSesion;
    private javax.swing.JLabel TituloIniciarSesion1;
    private javax.swing.JLabel TituloIniciarSesion2;
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToggleButton mostrarPass;
    private javax.swing.JPasswordField passContraseña;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
